package.json
src/transaction-runner.coffee
test/unit/add-hooks-test.coffee
test/unit/transaction-runner-test.coffee

Related to #124, computing content-length in executeTransaction not in configureTransaction, because transaction body can be modified in some before hook and content-length sensitive backends can hang forever.

Computing content-length in executeTransasction, fixing #124

---

package.json
src/transaction-runner.coffee
test/integration/cli-test.coffee

- fill all keys when `transaction` is executed
- fill `results` with results from Gavel.validate

Transaction runner fills all properties for test(step)

---

bin/dredd
scripts/cov
src/add-hooks.coffee
src/apply-configuration.coffee
src/command.coffee
src/configure-reporters.coffee
src/dredd.coffee
src/reporters/apiary-reporter.coffee
src/transaction-runner.coffee
test/integration/command-test.coffee
test/integration/dredd-test.coffee
test/unit/add-hooks-test.coffee
test/unit/command-test.coffee
test/unit/reporters/apiary-reporter-test.coffee
test/unit/transaction-runner-test.coffee

Because `clone` cannot clone `process.stdout`, custom configuration is passed to `Dredd` class as a second argument

Passing custom parameters to Reporters via JS API, logic from bin script to CoffeeScript

---

ApiaryReportingApi.md
src/blueprint-ast-to-runtime.coffee
src/reporters/apiary-reporter.coffee
test/unit/blueprint-ast-to-runtime-test.coffee
test/unit/reporters/apiary-reporter-test.coffee

- add used server endpoint to sent data via apiary-reporter otherwise is unknown (it is not sent in `headers.host`)
- send `uriTemplate` at origin, because expanded URL can be result of various endpoints

Enhance apiary reported json

---

package.json
src/sandbox-hooks-code.coffee
src/transaction-runner.coffee

- brings in `pitboss-ng` with support for `nodejs 0.12` / `0.10` / `iojs`

Use pitboss-ng npm instead of pitboss fork-git-url

---

package.json

- because proxyquire 1.5.x uses "fill-keys" package, which breaks add-hooks(-test)
> _a hotfix, real fix probably in next week(s) or month_

Freeze proxyquire to 1.4.x

---

docs/hooks.md
docs/usage.md
src/hooks.coffee
src/sandbox-hooks-code.coffee
src/transaction-runner.coffee
test/unit/dredd-test.coffee
test/unit/hooks-test.coffee
test/unit/sandbox-hooks-code-test.coffee
test/unit/transaction-runner-test.coffee

Making @nevir's work in  #223 even more excellent.
Introducing `beforeValidation` and `beforeEachValidation` hooks in standard and sandboxed mode. These hooks are executed after `Receive HTTP response` and before `Perform Gavel validation` in [Dredd's execution lifecycle](http://dredd.readthedocs.org/en/latest/usage/#dredd-execution-lifecycle)
Closes #221 and #223 
Workaround for #194

Support for before validation hooks

---

.travis.yml

Protagonist has issues building on iojs > 3.0.0 see. https://github.com/apiaryio/protagonist/issues/81

On Travis CI use iojs-2.5.0

---

src/dredd-command.coffee
src/hooks-worker-client.coffee

This really is more of a workaround rather than proper fix. Dredd needs
to refactor and rework of the language hooks handling, especially
graceful stopping as `SIGKILL` is definitely not the way to go.

Quick fix for the reporters issue #263

---

src/dredd.coffee
src/reporters/apiary-reporter.coffee
test/integration/cli-test.coffee
test/integration/dredd-test.coffee
test/unit/dredd-test.coffee
test/unit/reporters/apiary-reporter-test.coffee

Introducing _performRequestAsync to return callback filled with an error instead of fatal error in Apiary reporter.
Introduced change is triggered by need of assertion failure just after reporter start.

Apiary reporter not throwing anymore, only passing error to callback

---

CHANGELOG.md
package.json

**Support for Node 4 and 5, using Protagonist instead of Drafter.js**
- [#309](https://github.com/apiaryio/dredd/pull/309) Use protagonist instead of drafter (@ascripcaru)
- [#313](https://github.com/apiaryio/dredd/pull/313) Support node 4 and 5 in readme (@netmilk)
- [#310](https://github.com/apiaryio/dredd/pull/310) Travis build with node 4 and 5 (@ascripcaru)
- [#288](https://github.com/apiaryio/dredd/pull/288) Add info about supported Node.js versions (@w-vi)
**Documentation for GO hooks**
- [#281](https://github.com/apiaryio/dredd/pull/281) Add Go documentation (@snikch)
- [#315](https://github.com/apiaryio/dredd/pull/315) Go hooks to readme (@netmilk)
- [#314](https://github.com/apiaryio/dredd/pull/314) Updated logo image with GO (@honzajavorek)
- …

Version 1.0.2 release

---

docs/hooks-new-language.md

`hooks-node.md` ⇢ `hooks-nodejs.md`

Fixing links to Node(.js) hooks

---

docs/hooks-php.md

Just to make it explicit what versions are supported, as per [this](https://github.com/ddelnano/dredd-hooks-php/pull/8#issuecomment-168834122).

Add supported php versions to the php hook docs

---

src/dredd-command.coffee
src/hooks-worker-client.coffee
src/interactive-config.coffee
src/options.coffee
test/unit/dredd-command-test.coffee
test/unit/hooks-worker-client-test.coffee

By http://dredd.readthedocs.org/en/latest/ are PHP, Go available in Dredd but missing in `dredd init`

Add more hook languages into dredd init

---

.travis.yml

This is mainly to get rid of the annoying deprecation warnings in the Travis CI output:

Making sure Travis CI uses the latest npm

---

bin/dredd

The bf94183d9f introduced environment variable and merged `bin/dredd` and `bin/dredd-coverage`, which is cool, but I forgot to deal with different directories to require code from.
**This fixes collecting of coverage.**

Fix coverage collection in bin/dredd

---

docs/index.md

The link was referencing a local file that did not exist. The option is to either copy the CHANGELOG.md to the `doc` directory or link to the file in the GitHub repo. This PR does the latter.

Fix 404 CHANGELOG link

---

src/hooks-worker-client.coffee
test/unit/hooks-worker-client-test.coffee

Method setCommandAndCheckForExecutables was stubbed in tests and was never executed, although in real world it is executed every time someone uses hooks. Since for different hook languages different parts of the method are summoned, it was easy for many if/else branches to slip through error/trials or tests.
Due to this it was possible that it contained a lot of typos and errors, such as callbacks being never called or missing 'this'.
I believe this fixes #404, fixes #393 and possibly it could be also a solution for #384, but so far I can't be sure yet.

Hotfix of setCommandAndCheckForExecutables

---

scripts/cov
scripts/test
src/reporters/apiary-reporter.coffee
src/transaction-runner.coffee
test/integration/dredd-test.coffee
test/unit/reporters/apiary-reporter-test.coffee

Follow up of https://github.com/apiaryio/dredd/pull/331. I didn't want to work with @netmilk's branch directly as there was pretty nasty rebase needed and I was afraid to force-push and overwrite the original changes.
------
Closes https://github.com/apiaryio/dredd/pull/331, closes #289.

Fixing apiary reporter

---

README.md

Node versions are probably not so important information they would have to take up space in README.

Cosmetic changes in README

---

CHANGELOG.md
package.json

node-uuid was marked as insecure at https://nodesecurity.io/advisories/uuid_insecure-entropy-source-mathrandom

node-uuid is insecure - upgrade & version bump

---

docs/hooks-new-language.md
docs/overview.md

Fixes #425
Just a quick fix for `docs`. My method of action was to `grep` through the `docs` dir, and look for all instances of `localhost`. I did a quick replace to prepend `http://` to anywhere that localhost was used, but didn't have `http://`. I read this issue as only being relevant to the `docs` dir, so I left the `src` dir alone--though there are some instances of just `localhost` in there as well.  I ran `mkdocs serve` and things looked good. Let me know if this is what you were looking for. Thanks! Apiary rocks. :metal:

Update all local occurences of `localhost` in docs

---

package.json
src/dredd.coffee

Node 0.9 isn't supported by Dredd anymore. The shim isn't needed.

Remove 'setimmediate' shim

---

docs/quickstart.md

I already removed similar paragraphs from index.md and README.md, this slipped through the net. We support all recent versions of Node and we will always strive to do so. I consider such information redundant and hard to maintain in docs. If somebody wants to know, I'm okay with replying individually and sending them to CI config as a source of truth.

Remove supported Node versions from docs

---

src/blueprint-utils.coffee
src/handle-runtime-problems.coffee
test/unit/blueprint-utils-test.coffee
test/unit/dredd-test.coffee
test/unit/handle-runtime-problems-test.coffee

Preventing
```
(warning code 1) expected API name, e.g. '# <API Name>' on lines NaN-NaN, lines NaN-NaN
```

Preventing NaN in printed annotations

---

.gitignore
.npmignore

The package includes unnecessary stuff. That makes it harder to publish Dredd to npm on less reliable networks.

Slimmer NPM package

---

docs/usage.html
mkdocs.yml

Attempt to address #467 by @borsboom's workaround from https://github.com/rtfd/readthedocs.org/issues/1826#issuecomment-214753550. I think it will work for `/usage.html`, but I don't know how to do the same for `/usage/`.

Redirect /usage to /usage-cli

---

CONTRIBUTING.md
README.md
docs/hooks-nodejs.md
docs/index.md

Moving readthedocs.org to .io

---

src/transaction-runner.coffee

Making this change per @ddelnano's findings in https://github.com/snikch/goodman/pull/5#issuecomment-222054192.

Making sure transaction.request.body is used only if really present

---

.gitignore
docs/hooks-go.md
src/hooks-worker-client.coffee
test/unit/hooks-worker-client-test.coffee

This PR depends on [this](https://github.com/snikch/goodman/pull/5).  Once that is merged, the go hooks should be considered compliant with the hooks for other languages: php, ruby, python, perl, etc.
I tested the changes with this [repo](https://github.com/ddelnano/dredd-hooks-go-example).  I could not install dredd from a github repo since npm does not run prepublish and the necessary commands to do so I made these commits on my fork and made sure the examples worked.

Update docs and hooks worker client for go hooks

---

src/hooks-worker-client.coffee

This PR is to address when developing a hooks server from [dredd-hooks-template](https://github.com/apiaryio/dredd-hooks-template/blob/master/features/execution_order.feature#L78-L93).  If the hooks fail to modify the transaction sent back to dredd, it will crash dredd.  This is to present a more helpful error to the hook developer.  I just went through this for the second time (PHP and Go) and it took me a little digging before I realized I wrote the hookfile wrong.
I tried to add a test but it would have been difficult to be able to stub everything to the point where I could trigger the error.  I didn't get to spend enough time wrapping my head around some of the really long tests.

Add helpful error message if dredd hooks fail to modify transaction

---

package.json
src/dredd.coffee
src/transaction-runner.coffee
test/fixtures/multiple-responses.yaml
test/fixtures/swagger-multiple-responses.js
test/integration/dredd-test.coffee
test/unit/transaction-runner-test.coffee

Skipping non-2xx Swagger transactions by default, user can unskip them in hooks. This is because non-2xx responses for still the same request are not useful in most flows when testing a working server. Unlike API Blueprint, Swagger doesn't have an ability to specify specific request-response pairs, which address the problem.

Skipping non 2xx responses by default for Swagger

---

docs/usage-cli.md
src/dredd-command.coffee
src/options.coffee
test/integration/dredd-command-test.coffee
test/unit/config-utils-test.coffee

Implemented #339. Needed for https://github.com/apiaryio/dredd-example/ so it is able to pick both API Blueprint and Swagger during one build.
------
**Please ignore AppVeyor, it's not properly set up and actively used yet.**

--config option

---

CHANGELOG.md

This version was just backporting Node 6 support to 1.0.x line of releases and it somehow never made it to changelog.

Add v1.0.11 to changelog

---

CHANGELOG.md
docs/how-it-works.md
docs/how-to-guides.md
package.json

Dredd now supports `x-example` Swagger vendor extension property.

Support for x-example (v1.5.0)

---

package.json

Getting the `devDependencies` badge green again.

Upgrade Mocha to the latest version

---

.travis.yml
CONTRIBUTING.md
scripts/test-hooks-handlers.coffee

Changed integration tests of hooks handlers so they:
- report under PRs - they create statuses on GitHub now
- do not spawn full matrix of dependent build language versions - now they select just one
- do not time out - closes https://github.com/apiaryio/dredd/issues/374
- run only once! (currently they run twice for every new Dredd version)
- are documented in `CONTRIBUTING.md`
- use @ApiaryBot's GitHub token, not mine
Since the tests now run under every PR, the triggering logic was simplified and string `tests hook handlers` in the commit message won't have any effect anymore.
Basically, the aim is to make the tests more user-friendly and more "throwaway" and omnipresent. This will fix some current issues as well as it should enable us to get closer to Semantic Releasing (#438, #440) …

Tests of hooks handlers now report under PRs

---

package.json

Closes https://github.com/apiaryio/dredd/issues/578. Uses https://github.com/apiaryio/commonjs-html-prettyprinter.

Address security issue in the HTML package

---

.travis.yml

It has been one month of testing both versions of Drafter and there has been no issues. I'm removing the matrix so our tests can run two times faster again.

Remove JS/CPP testing matrix

---

docs/how-to-guides.md
package.json
test/fixtures/regression-615.apib
test/fixtures/swagger-multiple-responses.js
test/fixtures/swagger-transaction-names.js
test/integration/dredd-test.coffee
test/regressions/regression-319-354-test.coffee
test/regressions/regression-615-test.coffee

**BREAKING CHANGE**
This change closes https://github.com/apiaryio/dredd/issues/615 and also closes https://github.com/apiaryio/dredd/issues/558. 
Added a regression test, which fails on current Dredd and is expected to pass when https://github.com/apiaryio/dredd-transactions/pull/61 gets merged and released. The change is breaking for some API Blueprint users and will bump Dredd's major version.
Added a test, which fails on current Dredd and is expected to pass when https://github.com/apiaryio/dredd-transactions/pull/63 gets merged and released. Updated all related documentation. The change is breaking for all Swagger users and will bump Dredd's major version.

Solution for #615 and #558 (breaking)

---

package.json
scripts/print-installation-guidelines.js

For no obvious reason, npm scripts written in CoffeeScript can cause problems. This change avoids any problems all together, since it introduces rewrite of the script, which is being run every time after installation, into a plain ES5 JavaScript.
This fixes https://github.com/apiaryio/dredd/issues/629 and supersedes https://github.com/apiaryio/dredd/pull/630.

Rewrite print installation guidelines in JS

---

ApiaryReportingApi.apib
ApiaryReportingApiAnonymous.apib

Just a small typos-fix
Should not break anything, since Dredd was using `Attributes`-generated JSON-Schema for validating the bodies.

Fix "strings" of Boolean values in blueprint files

---

src/transaction-runner.coffee

Remove redundant line

---

package.json

Dredd version 2.2.0 cannot be installed due to this 😞 Thanks very much @XVincentX for discovering this right away! 💕 👍 🇮🇹

Development dependency promoted, fixes last release

---

README.md

The CHANGELOG.md file isn't present in the repo anymore and GitHub releases are used instead. Similar link was fixed in docs' index.md, but not in README.md.

Fix broken changelog link

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
docs/contributing.md
package.json

Dredd uses Conventional Changelog to automate releasing and changelog generating. It's crutial not to make mistakes in formatting of the commits. Of course, there are [contributing docs](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) on this topic, but prevention is always better - humans make mistakes :)
- #438

Use conventional changelog linter

---

package.json
src/dredd-command.coffee
src/hooks-worker-client.coffee
src/which.coffee
test/unit/hooks-worker-client-test.coffee

I want to add an experimental AppVeyor (Windows-based) CI builds to [dredd-example](https://github.com/apiaryio/dredd-example/). This PR is a small step towards better Windows support.
- **The `--server` option should now work also on Windows.** I manually verified that this change is an improvement and enables running the server command on Windows.
- **Removed direct subprocess call to `which` command, which isn't present on Windows.** This is an obvious blocker for non-JS hooks being supported on Windows and I just wanted to have it out of our way. I didn't verify if it actually enables anything right away.
- #204

Make spawning server command and 'which' Windows-compatible

---

package.json
src/hooks-worker-client.coffee
src/reporters/apiary-reporter.coffee

Author of node-uuid decided to deprecate for reasons I do not know and
replace it with uuid.

Replace deprecated uuid module

---

docs/hooks-python.md

Improving the documentation
None

docs: Add link to more examples in python hooks repo

---

docs/installation.md

...because it extremely speeds up installation and in some situations you want exactly that:
- demoing Dredd to people, including installation
- demoing Dredd & CI to people, the CI build takes ages when it compiles C++11 drafter
- avoid any C++11 compilation attempts
- installing in CI
- possibly more...

Add advice about --no-optional

---

docs/hooks-ruby.md

docs: Fix typo in hooks-ruby code snippet

---

.travis.yml

Travis CI offers two kinds of runtimes. Simplified,
- one is distro-based allows you to use `sudo` and install all kind of stuff on your own,
- second is container-based, has more limitations, but should be newer and faster.
Dredd did need `sudo` previously, because of C++11 compilation of the [drafter](https://github.com/apiaryio/drafter). Since drafter is now also JS-only, Dredd does not need the distro-based architecture anymore. This PR removes `sudo` and all related options from the Travis CI configuration. The PR also adds `--no-optional` to `npm install`, which forces npm to ignore C++11 compilation of drafter and to use the JS version directly. That should improve build time.
I did try to migrate Dredd's test suite to non-sudo builds previously already, but the test suite did not …

Use Travis CI without sudo

---

.travis.yml

Please ignore AppVeyor builds. AppVeyor is present only to test the [`honzajavorek/appveyor`](https://github.com/apiaryio/dredd/tree/honzajavorek/appveyor) branch (in progress) and is expected to fail everywhere else.
In https://github.com/apiaryio/dredd/pull/689 I thought I ensured Dredd's test suite runs on Travis CI without `sudo`. That was wrong assumption, because I've removed `sudo` flag altogether. However, the flag's default value depends on when the repository was first connected to Travis CI. See [docs](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments).
For that reason, I'm explicitly stating in the `.travis.yml` file that architecture without `sudo` should be used.
- https://github.com/apiaryio/dredd/pull/689 (previous attempt)
- Closes …

Do not rely on Travis CI default value for 'sudo' flag

---

docs/how-it-works.md
docs/how-to-guides.md

We should be transparent about this.

Note on security - Apiary Reporter

---

docs/how-to-guides.md

Adds [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefix in front of the commit in https://github.com/apiaryio/dredd/pull/695.
Closes https://github.com/apiaryio/dredd/pull/695.

Fix broken link

---

docs/hooks-go.md
src/dredd-command.coffee
src/hooks-worker-client.coffee
test/unit/hooks-worker-client-test.coffee

Its best practice in go to allow `go get` to install the package's binaries for you.
Please see https://github.com/snikch/goodman/issues/17

docs: update instructions for go best practices

---

.travis.yml
package.json
provisioning.sh

Node 0.10 and 0.12 are not supported anymore, so we're removing them from CI and we're removing any related workarounds.
- See https://github.com/apiaryio/dredd/issues/660 for the list of workarounds which this PR fixes.
- See https://github.com/nodejs/LTS#lts-schedule for details on why Node.js 0.10 and 0.12 can be both considered as officially dead since 2016-12-31.
- This is a breaking change, since we're dropping support of certain runtimes. Merging this PR should release **Dredd 3.0.0**.
Waits for https://github.com/apiaryio/dredd-transactions/pull/69 and https://github.com/apiaryio/gavel.js/pull/86, closes https://github.com/apiaryio/dredd/issues/660.

Drop support for Node 0.10 and 0.12

---

docs/contributing.md
docs/hooks-go.md
docs/hooks-perl.md
docs/hooks-php.md
docs/hooks-python.md
docs/hooks-ruby.md
test/integration/cli/cli-test.coffee
test/integration/cli/reporters-cli-test.coffee
test/unit/hooks-worker-client-test.coffee

I prefer to stick to UNIX / GNU conventions. This style of options is also less error-prone when trying to test Dredd on Windows.
- #204

Prefer --option=value (GNU-style) format of long options

---

test/integration/cli/api-description-cli-test.coffee

The test checks a situation when Dredd is trying to read an existing path, but the path isn't a file, it is a directory. The test expects an exception will occur.
This change ensures the target is existing directory and that it is on a file system, which is native to the underlying operation system. E.g. when trying to read a directory as a file on NFS on Windows (can happen easily in VirtualBox, for instance), the operation won't throw an exception, but will read an empty string.
- #204

Use home directory

---

test/integration/cli/helpers.coffee
test/integration/cli/server-process-cli-test.coffee

This seems to be the only sane way to spawn subprocess on both Windows and UNIX in Node.js.
- #204

Use cross-spawn instead of exec

---

test/mocha.opts

On Windows spawning a subprocess can take extreme times.
- #204

Force Mocha to wait longer

---

package.json
src/transaction-runner.coffee
test/unit/transaction-runner-test.coffee

I'm not sure why Dredd uses custom implementation for requesting the server under test. I experienced some problems with it on Windows. This PR introduces the `request` library as a way to request the server under test. It should also help in the future to support proxies, because the library supports it out of the box 😎 
- #204 
- #51 & #591

Use the request library instead of custom implementation

---

src/dredd-command.coffee
src/hooks-worker-client.coffee
test/integration/cli/server-process-cli-test.coffee

If hook handler command string is 'node hello.js --option=1', we want to find out only whether the 'node' executable is present in the system. For that reason, we first parse the command and lookup (using 'which') only the actual command part, without parameters. Looking up the whole string may or may not work on UNIX/Linux, but it does not work at all on Windows.
The PR also contains several minor improvements:
- Improved logging (wording, information) in `DreddCommand` class
- Using spawn instead of exec for dynamically determining the package version (debugging info in `DreddCommand` class)
The coverage has dropped because there is one more relevant line of code in part of Dredd, which is historically uncovered by tests. It's the part which takes care of killing server/hook handler …

Parse hook handler command string, lookup only the command part

---

docs/usage-cli.md
docs/usage-cli.md-template

Markdown syntax for newlines is two spaces at the end of the line (see https://daringfireball.net/projects/markdown/syntax#p for reference). But such syntax is very prone to many problems:
*  It's invisible to anyone who opens the file and doesn't know about it in advance. It's very easy to miss the spaces when editing and to accidentally remove them.
*  Many editors intended for coding trim trailing spaces. Again, since the syntax is invisible and many don't even know about it, they often don't even notice during code review (the only place where it turns out to be visible at least a bit).
For that reason, let's use explicit `<br>` instead of two spaces.
This PR corrects mistakes in https://github.com/apiaryio/dredd/pull/732.

Prevent newlines from disappearing

---

test/integration/cli/cli-test.coffee
test/integration/cli/reporters-cli-test.coffee
test/integration/regressions/regression-319-354-test.coffee
test/unit/add-hooks-test.coffee
test/unit/configure-reporters-test.coffee
test/unit/dredd-test.coffee
test/unit/handle-runtime-problems-test.coffee
test/unit/hooks-worker-client-test.coffee
test/unit/prettify-response-test.coffee
test/unit/reporters/apiary-reporter-test.coffee
test/unit/reporters/base-reporter-test.coffee
test/unit/reporters/cli-reporter-test.coffee
test/unit/reporters/dot-reporter-test.coffee
test/unit/reporters/html-reporter-test.coffee
test/unit/reporters/markdown-reporter-test.coffee
test/unit/reporters/nyan-reporter-test.coffee
test/unit/reporters/x-unit-reporter-test.coffee
test/unit/transaction-runner-test.coffee

`assert.isOk()` is present in current Chai docs, `assert.ok()` is now just an alias to support older code.
Follow-up to #737

Use Chai's assert.isOk() instead of assert.ok()

---

src/transaction-runner.coffee

I use Dredd with a hooks handler in Go and my API blueprint contains a request without body (only the headers are important). In this scenario, the current release produces the following error:
```
verbose: Running 'before' hooks
verbose: Calculating Content-Length of the request body
buffer.js:363
throw new TypeError('"string" must be a string, Buffer, or ArrayBuffer');
^
TypeError: "string" must be a string, Buffer, or ArrayBuffer
at Function.byteLength (buffer.js:363:11)
at TransactionRunner.setContentLength (/usr/local/lib/node_modules/dredd/lib/transaction-runner.js:496:69)
at TransactionRunner.executeTransaction (/usr/local/lib/node_modules/dredd/lib/transaction-runner.js:505:10)
at TransactionRunner.executeTransaction (/usr/local/lib/node_modules/dredd/lib/transaction-runner.js:3:57 …
```

fix: don't set Content-Length for empty request bodies

---

src/hooks-worker-client.coffee

- [`yup` ] To write docs
- [ `nope`] To write tests
- [`npm run lint` doesn't work] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`

attempt to use gobin when provided and fall back to gopath

---

docs/how-to-guides.md

Current examples won't work. There's a typo regarding where the request headers live in the transaction object.

Fix hooks examples

---

test/integration/helpers.coffee

When concatenating stdout and stderr to get the whole output, then the output contains first stdout and then stderr. For output to be useful, it needs to contain stdout and stderr entwined, in the same order as can be usually seen when the command is ran in the console.

Have command ouput in the right order (test helpers)

---

src/child-process.coffee
src/dredd-command.coffee
test/integration/child-process-test.coffee
test/integration/helpers.coffee

When working with spawned subprocesses, it seems like under some circumstances the 'close' event isn't emitted on Linux when the process terminates. The 'exit' event seems to be called consistently accross operating systems.
- Close https://github.com/apiaryio/dredd/issues/670#issuecomment-291900957

Listen on 'exit' event instead of 'close'

---

docs/installation.md

The Dredd Example is linked, but the link is missing at the bottom of the Markdown document.

Add missing reference to the Dredd Example

---

package.json

The sync-exec library is now used only in the hook handlers integration tests. Moreover, the tests are currently turned off (for various reasons: #672, #644, and more). For that reason, it should be only a dev dependency. Also, this should resolve the red Snyk badge as a side-effect (only production dependencies are being continuously checked for vulnerabilities).
- https://snyk.io/vuln/npm:sync-exec:20160124

The sync-exec should be just a dev dependency

---

src/transaction-runner.coffee

Because the current syntax is broken.
I think an issue https://github.com/apiaryio/dredd/issues/731 is because of that. Also, I stumbled upon it today when having `+ Response 200 (content-type: application/json; charset=UTF-8)` where `content-type: application/json` is clearly a wrong mime-type. After removing `content-type: ` it worked fine.
Docs not related. I didn't write any tests because `validateTransaction` has no tests and this is really a syntax error, unfortunately not figured out by Coffee.

fix(transaction-runner): use => in validateTransaction gavel callbacks

---

package.json

One dependency of Gavel.js was specified as `josdejong/jsonlint`, which doesn't work in restricted networks. While it's difficult to remove dependency on a GitHub repository at the moment, we can at least specify it as `git+https://git@github.com/josdejong/jsonlint.git`, which should be more portable.
Related to https://github.com/apiaryio/gavel.js/pull/92

Make Dredd installable in restricted network

---

src/reporters/apiary-reporter.coffee
test/unit/reporters/apiary-reporter-test.coffee

If Apiary API URL is configured with a trailing slash, it causes double slashes and may cause further problems.

Remove trailing slash from Apiary API URL

---

docs/hooks.md
docs/how-to-guides.md
docs/quickstart.md
docs/requirements.txt

This PR uses [pygments-apiblueprint](https://github.com/kylef/pygments-apiblueprint) to add syntax highlighting for API Blueprint to the rendered documentation on readthedocs. While pygments-apiblueprint is not perfect, it is certainly better than no syntax highlighting. If you spot any rendering issues with API Blueprints feel free to open issues over there and I'll try fixing (I did find https://github.com/kylef/pygments-apiblueprint/issues/1 which I'll fix but no need to block this PR).
Note, this also version locks all of the mkdocs/pygments and related dependencies so that they are not changed and break the docs. If you'd rather not lock the versions I can change requirements.txt to not specify versions, but I think it would be a good idea to lock them so documentation doesn't …

Syntax highlight API Blueprint in documentation

---

.github/CONTRIBUTING.md
docs/installation.md

Installation of Dredd in restricted environment isn't completely straightforward. I added a section about the necessary steps. At the same time, I tried to simplify other sections as well and to make them more use-case-oriented.
- https://github.com/apiaryio/gavel.js/issues/83

Reformulate installation guidelines and add section about proxies

---

scripts/coverage.sh

The `coverage.sh` won't set proper exit status code in case the tests are failing. The exit status code of `npm test` will get forgotten and the `coverage.sh` script will always finish with success 😱 (luckily, AppVeyor holds our back because of #763 - it does not use the `npm run test:coverage` script).
- https://github.com/apiaryio/dredd/pull/726

Fix exit status for failing builds

---

test/fixtures/multiple-examples.apib

API Blueprint format supports just indentation with 4 spaces. Different formatting may cause issues and parser warnings.

Use 4 spaces as indentation

---

docs/how-it-works.md
docs/how-to-guides.md

Currently, in the API Blueprint  the default JSON Schema inferred by Gavel or generated from [MSON](https://github.com/apiaryio/mson) (the Attributes section) is quite benevolent. That results in Dredd tests passing easily even though the payloads are missing attributes or having extra attributes. User is given the freedom to specify stricter conditions and achieve stricter testing if they wish.
While such freedom is intended, usually users don't know about it and just expect Dredd to test everything strictly out of the box. That's why Dredd docs should explicitly mention how benevolent Dredd is and how to make it stricter (`fixed-type`, `fixed`, `required`, custom JSON Schema, etc.).
Fixes https://github.com/apiaryio/dredd/issues/232
Fixes https://github.com/apiaryio/dredd/issues/710
See …

Document how to make Dredd validation stricter

---

docs/data-structures.md
src/reporters/base-reporter.coffee
test/unit/reporters/base-reporter-test.coffee

See #376 
Sometimes test.start is transformed into a string (I haven't figured out where - maybe from a hooks handler). The duration can no longer be calculated in that case.

Fix #376 (NaNms duration)

---

src/transaction-runner.coffee
test/unit/transaction-runner-test.coffee

Dredd is following 3xx redirections (as a result of a GET request, not for POST requests) because that is the default behavior implemented in the `request` package. This makes it impossible to validate API specs that produce a redirection.
#795

#795: HTTP client should not follow redirects

---

test/integration/dredd-command-test.coffee
test/integration/dredd-test.coffee
test/unit/add-hooks-test.coffee
test/unit/config-utils-test.coffee
test/unit/dredd-command-test.coffee
test/unit/dredd-test.coffee
test/unit/handle-runtime-problems-test.coffee
test/unit/hooks-log-test.coffee
test/unit/hooks-worker-client-test.coffee
test/unit/interactive-config-test.coffee
test/unit/reporters/html-reporter-test.coffee
test/unit/reporters/markdown-reporter-test.coffee
test/unit/reporters/x-unit-reporter-test.coffee
test/unit/transaction-runner-test.coffee

Sinon has deprecated the `sinon.stub(obj, 'meth', fn)` notation and replaced it with `sinon.stub(obj, 'meth').callsFake(fn)`. [See the migration guide.](http://sinonjs.org/releases/v2.0.0/migrating-to-2.0/#stubcallsfake-replaces-stubobj-meth-fn)
This is a follow-up to https://github.com/apiaryio/dredd/commit/31fe7b549221fc848e89f5682818d2c25393bd56.

Update sinon.stub() calls from deprecated to the new syntax

---

package.json
test/integration/cli/cli-test.coffee
test/integration/cli/reporters-cli-test.coffee
test/integration/dredd-test.coffee
test/unit/add-hooks-test.coffee
test/unit/configuration-test.coffee
test/unit/dredd-test.coffee
test/unit/hooks-log-sandboxed-test.coffee
test/unit/hooks-log-test.coffee
test/unit/hooks-test.coffee

Bundled chai version starts to be outdated.
**BREAKING CHANGE:** The chai library is available in the sandboxed JS hooks' interface. For that reason, it is also a part of Dredd's public interface (and for the same reason it's not a devDependency, but dependency). The new version of chai is not backwards compatible in some cases, which means this is a breaking change.
**HOW DO ONE KNOWS ALL OCCURRENCES ARE ADDRESSED?** Simple! The tests would crash/fail in case I'd forget to change something 😄

Upgrade chai

---

docs/hooks-new-language.md
docs/hooks.md
docs/usage-cli.md
src/add-hooks.coffee
src/options.coffee
test/integration/cli/cli-test.coffee
test/unit/add-hooks-test.coffee

Currently, Dredd provides hook file paths / globs to hook handlers in the same form (untouched) as they are passed via the CLI. Since every language has its own implementation of glob pattern resolution, it can potentially lead to problems with wrong execution order of hook files.
With the changes introduced in this pull request, Dredd will now resolve glob patterns, matched file paths resolves to their absolute form, sorts them alphabetically and then passes to hook handlers.
Resolves #680 and resolves #742.

Resolve glob patterns before passing them to hook handlers

---

src/reporters/x-unit-reporter.coffee
test/integration/child-process-test.coffee
test/unit/transaction-runner-test.coffee

To make sure that, if one day you'll be willing to use `decaffeinate`, it will convert the code with no complains.
#705

Refactor: make some parts more decaffeinate-friendly

---

src/dredd-command.coffee

Currently, Dredd returns wrong exit code (`O`) when test(s) fail (should return `1`). This change fixes the problem.
Resolves https://github.com/apiaryio/dredd/issues/818.

Hotfix: Return correct exit code when tests fail

---

README.md

Jenkins link was opening too slowly. The change will avoid redirect and thus open faster.

Fix jenkins link

---

docs/conf.py

Local links do not work on current version of the docs. This fix is tested on https://dredd.readthedocs.io/en/honzajavorek-fix-local-links/ and it looks like it resolves the problem.
Fixes https://github.com/apiaryio/dredd/issues/825.

Fix internal links in docs

---

.travis.yml

With current setup, the CI build continues to run tests even if linter fails. This is unnecessary waste of time & resources.

Fail CI build as soon as there's something failing

---

bin/dredd

Collecting coverage should not abuse Dredd's interface for overriding the `exit` function. The new way is unobtrusive.

Do not abuse exit override to collect coverage

---

src/transaction-runner.coffee
test/fixtures/request/application-json.apib
test/fixtures/request/application-x-www-form-urlencoded.apib
test/fixtures/request/multipart-form-data.apib
test/fixtures/request/text-plain.apib
test/integration/helpers.coffee
test/integration/request-test.coffee

Current implementation of multipart request bodies is broken. See https://github.com/apiaryio/dredd/issues/786.
In https://github.com/apiaryio/dredd/pull/734 Dredd's custom implementation of HTTP requesting was replaced with the `request` library. There is some special handling of multipart requests, solving https://github.com/apiaryio/api-blueprint/issues/401, which modifies the body payload and also modifies the `Content-Length` header accordingly. This wasn't updated with introduction of the `request` library. That resulted in the `Content-Length` being sent with incorrect number, causing the server under test to hang, waiting for more bytes.
My changes makes the code dealing with https://github.com/apiaryio/api-blueprint/issues/401 a lot simpler and more functional (no side effects). …

Modify multipart body and calculate Content-Length in the right order

---

.travis.yml

See https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming. Dredd test suite has some issues running on `trusty`. We have to investigate and fix those before upgrading.

Pin Travis to 'precise' until we explicitly migrate to 'trusty'

---

.travis.yml

See https://blog.travis-ci.com/2017-05-11-introducing-build-stages and https://docs.travis-ci.com/user/build-stages. Looks like a cool feature which could save some resources (if not now, then in the future). Also the stages could make the build more readable for Dredd contributors.
- [Last `master` build](https://travis-ci.org/apiaryio/dredd/builds/262662384) took 35 mins total time
- This branch built in 33 mins total time twice, so I don't think it should have any kind of performace impact
The PR also pins npm to v4 on Travis CI.
- https://github.com/apiaryio/dredd/issues/828

Introduce Travis CI build stages and pin npm version

---

.github/CONTRIBUTING.md
README.md
docs/hooks-nodejs.md
docs/how-it-works.md
docs/how-to-guides.md
docs/index.md
docs/installation.md
docs/quickstart.md
docs/redirects.yml

https://swagger.io/specification/ now features the new 3.0 specification, but Dredd only supports Swagger 2.0. All links to supported Swagger features should now link to the old spec, which is still available on GitHub.
With this change, also other minor fixes were made in several links. All has been locally checked with `npm run docs:build` and `npm run docs:lint`.
- https://github.com/apiaryio/dredd/issues/828
- #775

Fix several links, use Swagger 2.0 specs as a reference

---

README.md
docs/hooks-rust.md
docs/index.md
src/dredd-command.coffee
src/hooks-worker-client.coffee
src/interactive-config.coffee
src/options.coffee
test/unit/dredd-command-test.coffee
test/unit/hooks-worker-client-test.coffee

Hey there! 👋 
I wrote a hooks-handler for Rust: https://github.com/hobofan/dredd-hooks-rust.
This PR adds all the additional parts on the Dredd side that make a hooks integration more pleasant to use, similar to the other languages. I closely followed the Go integration, so I hope I didn't miss anything. The only thing I know that is missing is the Rust logo in the README, which I hope is okay for now.
Looking forward to your feedback!

feat: add integration for Rust hooks

---

docs/hooks-new-language.md

CLOSES #271 
Also adresses my question of #834, what the array of transaction objects contains.
#271, #834

docs: fix inconsistencies in hook socket message docs

---

.travis.yml

In https://github.com/apiaryio/dredd/pull/849 Travis CI stages were introduced. This has broken automatic releasing: https://github.com/semantic-release/semantic-release/issues/390
- https://github.com/apiaryio/dredd/pull/849
- https://github.com/semantic-release/semantic-release/issues/390

Make sure Semantic Release works with build stages

---

.travis.yml
scripts/semantic-release.sh

Sequel to https://github.com/apiaryio/dredd/pull/854, inspired by Hollywood™
Works around [this line of code](https://github.com/semantic-release/travis-deploy-once/blob/54effadf0f3c3b90500b495218f05cf80e95b446/src.js#L12). The stage will never start without the previous stages being passing, so the check is pointless now.
- https://github.com/apiaryio/dredd/pull/854
- https://github.com/semantic-release/semantic-release/issues/390#issuecomment-321769702

Make sure Semantic Release works with build stages (sequel)

---

docs/hooks-new-language.md

Correct typo which could confuse the reader.

docs: correct typo in tcp message event afterEach

---

src/child-process.coffee
src/dredd-command.coffee
test/integration/cli/server-process-cli-test.coffee

This PR fixes the issue with wrong CLI exit code when running Dredd with incorrect argument to `--server` command (reported in https://github.com/apiaryio/dredd/issues/818).
Closes #838

Return correct exit code when server fails to start

---

test/integration/cli/cli-test.coffee
test/integration/dredd-test.coffee
test/unit/dredd-command-test.coffee

Correct various typos

---

package.json

This PR adds `build:watch` script to `package.json` to enable incremental compilation as requested in https://github.com/apiaryio/dredd/issues/867.
- Closes https://github.com/apiaryio/dredd/issues/867

Add watch script for auto recompile

---

docs/data-structures.md
package.json

Seems like the docs are out of sync with the transaction data structure.
https://github.com/snikch/goodman/pull/37
I still haven't completed verified this is the case since the bug report does not have much detail but skimming the dredd source code I see [this](https://github.com/apiaryio/dredd/blob/acecae523d71b71f47cc66e8587d83e5104ebded/src/transaction-runner.coffee#L310).

Update docs to reflect actual data

---

docs/data-structures.md
src/transaction-runner.coffee
test/integration/cli/cli-test.coffee
test/integration/dredd-test.coffee
test/integration/regressions/regression-319-354-test.coffee
test/unit/transaction-runner-test.coffee

The primary reason for this change is that test IDs are non-unique and that makes test output hard to understand. This PR adds the `(###)` to the transaction ID so that a 200 is distinctly different from a 204, 401, 404, etc... 
```
info: Successfully connected to hooks handler. Waiting 0.1s to start testing.
pass: POST (204) /channelmapper/v1/channel duration: 25ms
skip: POST (401) /channelmapper/v1/channel
skip: POST (404) /channelmapper/v1/channel
pass: GET (200) /v1/channel/9cd4342be duration: 25ms
skip: GET (401) /v1/channel/9cd4342be
pass: GET (404) /v1/channel/9cd4342be duration: 16ms
complete: 3 passing, 0 failing, 0 errors, 3 skipped, 6 total
```
* Closes https://github.com/apiaryio/dredd/issues/866
- [✔] To write docs
- [✔] To write tests
- [✔] To put [Conventional …

Add status codes to test ID and Dredd output

---

package.json
test/fixtures/warning-swagger.yaml

Currently, tests on `master` branch do not pass due to two issues - first, `dredd-transactions` got implicitly bumped to version `4.4.0` (which introduces a breaking change due to upgrade of `fury-adapter-swagger` to version `0.14.2`) and second, `warning-swagger.yaml` test fixture was not producing a warning anymore.

Fix broken master

---

docs/installation.md

Because on Windows there's no node-gyp error, there's python error.

Add "python" error for Windows users

---

src/add-hooks.coffee
test/unit/add-hooks-test.coffee

Just a simple mistake with the compare function.
I'm not sure if adding extra hook files for testing is actually helpful?  On my machine they are the smallest number of files needed to trigger the bug but now the bug is fixed they are kind of messy.

fix: Hook files are not always executed in alphabetical order (#890)

---

src/transaction-runner.coffee

It might be helpful for people suffering from maximum call stack exceeded issues eg #225 
#225 could be fixed, I haven't tested but it at least solves my issues.
Tests break as many assume synchronous returns.
If someone else wants to pick it up and run with it they are welcome to.

Limit stack depth to avoid maximum call stack exceeded issues

---

package.json

The old `inquirer` version pulls down a lot of old dependencies and prevents deduplication.
Fixes #768
Tested `dread init` manually with a couple of variations, everything works fine.

chore: update inquirer to version 3.3.0

---

src/configure-reporters.coffee
src/options.coffee
test/integration/cli/reporters-cli-test.coffee
test/unit/configure-reporters-test.coffee

`xunit` is the better parameter for reporter rather than `junit`. `junit` is still supported until it is decided to be removed (https://github.com/apiaryio/dredd/issues/888#issuecomment-337265911).
Resolves https://github.com/apiaryio/dredd/issues/888

Added support for reporter xunit parameter

---

appveyor.yml
docs/how-it-works.md
docs/how-to-guides.md
package.json
src/transaction-runner.coffee
test/fixtures/regression-893.yaml
test/fixtures/regression-897-body.yaml
test/fixtures/regression-897-schema.yaml
test/fixtures/request/application-x-www-form-urlencoded.yaml
test/fixtures/request/multipart-form-data.apib
test/fixtures/request/multipart-form-data.yaml
test/fixtures/response/204-205-body.apib
test/fixtures/response/204-205-body.yaml
test/fixtures/response/empty-body-empty-schema.apib
test/fixtures/response/empty-body-empty-schema.yaml
test/fixtures/response/empty-body-hooks.js
test/fixtures/response/empty-body.apib
test/fixtures/response/empty-body.yaml
test/fixtures/swagger-multiple-responses.js
test/integration/dredd-test.coffee
test/integration/regressions/regression-152-test.coffee
test/integration/regressions/regression-615-test.coffee
test/integration/regressions/regression-893-897-test.coffee
test/integration/request-test.coffee
test/integration/response-test.coffee
test/unit/transaction-runner-test.coffee

- Solitary default responses in Swagger are now treated as HTTP 200 #893
- Fixes how Dredd handles empty bodies and empty schemas #556, #897
- Pins peer dependencies #905
- In Swagger, JSON media types with parameters (such as charset) are now recognized as JSON #553, #883
- Fixed handling of multipart/form-data in Swagger #711
- Closes https://github.com/apiaryio/dredd/pull/896 (deprecates)
- Fixes #893, fixes #556, fixes #897, fixes #905, fixes #711, fixes #553
- Related https://github.com/apiaryio/dredd/issues/883, https://github.com/apiaryio/dredd-transactions/pull/119

Upgrade Dredd Transactions and fix tons of issues

---

docs/how-to-guides.md

Because otherwise the docs build errors 😱 
Remedy of https://github.com/apiaryio/dredd/pull/906

Fix internal link

---

test/unit/add-hooks-test.coffee

Sometimes I happen to have extraneous stuff in the repo, such as [virtualenv](https://docs.python.org/3/library/venv.html). It can contain basically anything. The tests are so vague they can match anything 🙂 Let's make them more specific.

Make sure addHooks() tests don't match unexpected stuff

---

test/integration/child-process-test.coffee

Because we shouldn't spend our lives by waiting until unnecessarily slow tests finish.

Make child process tests faster

---

package.json

Prevents https://github.com/jashkenas/coffeescript/issues/4806. I raised the patch number to be aligned with what was previously in Dredd Transactions.

Pin CoffeeScript version

---

src/get-go-bin.coffee
src/hooks-worker-client.coffee
test/unit/get-go-bin-test.coffee
test/unit/hooks-worker-client-test.coffee

According to Go docs, the following cascade should be the correct way to determine where to look for the binaries:
- $GOBIN
- $GOPATH/bin
- $(go env GOPATH)/bin
Review from @ddelnano / @snikch appreciated. I'm also adding all the Go fans I know as reviewers, because I'm not really skilled in Go at all.
- Closes https://github.com/apiaryio/dredd/pull/835

Use GOPATH if GOBIN isn't set

---

docs/installation.md

Fix typo on the installation page

---

src/transaction-runner.coffee

To fix #931. We're not sure why this change has introduced the problem and there are no tests confirming the issue, but we're able to replicate it.
- #931, https://github.com/apiaryio/dredd/pull/901

Partially revert e8b534a to fix #931

---

src/dredd.coffee
src/reporters/apiary-reporter.coffee
src/transaction-runner.coffee
test/integration/cli/api-blueprint-cli-test.coffee
test/integration/cli/api-description-cli-test.coffee
test/integration/cli/reporters-cli-test.coffee
test/integration/cli/server-process-cli-test.coffee
test/integration/cli/swagger-cli-test.coffee
test/unit/dredd-test.coffee

Failure of reporters should not interfere with testing itself.
- Fixes https://github.com/apiaryio/dredd/issues/683

Print reporter errors, but do not treat them as fatal

---

src/add-hooks.coffee
src/dredd.coffee
src/resolve-hookfiles.coffee
test/integration/cli/api-description-cli-test.coffee
test/integration/cli/cli-test.coffee
test/unit/add-hooks-test.coffee
test/unit/dredd-test.coffee
test/unit/resolve-hookfiles-test.coffee

Dredd should treat non-existing files (or globs evaluating to no files) as user error. This PR just finalizes @jgjadaoag's amazing work in https://github.com/apiaryio/dredd/pull/909.
We want to have this done as soon as possible so there are no open Pull Requests and we could decaf the codebase - #705.
- Fixes #378
- Closes https://github.com/apiaryio/dredd/pull/909

Throw error when additional path doesn't exist

---

package.json

Looks like the only use of `colors` was removed in 91a4d585691fcc0a04fde06a491be9bbdc1dd073. Let's have one less dependency 🎉

chore: remove the unused dependency colors

---

.travis.yml

We should have been using `trusty` for a long time, but the tests has been flaky/failing - https://github.com/apiaryio/dredd/issues/828. Now I tried to address the issue and I discovered the tests are not failing anymore 🤷‍♂️ I'm not sure why exactly, but hey, let's rejoice and migrate to `trusty`!
- Closes https://github.com/apiaryio/dredd/issues/828

Use "trusty" at Travis CI

---

package.json

The request body is not generated when ```format: uuid``` is present and there is no error message as of why. This has been fixed by https://github.com/apiaryio/fury-adapter-swagger/pull/156 (thanks, @kylef!).
Releases https://github.com/apiaryio/fury-adapter-swagger/pull/156
Fixes https://github.com/apiaryio/dredd/issues/941

Generate request body for "format: uuid"

---

src/handle-runtime-problems.js

Errors were missing a space between the annotation and line number (if present)
Before:
```
error: Parser error in file 'swagger.yaml': Data does not match any schemas from 'oneOf'on line 365
```
After:
```
error: Parser error in file 'swagger.yaml': Data does not match any schemas from 'oneOf' on line 365
```
- ~[ ] To write docs~
- ~[ ] To write tests~

chore: Adding space before error line number

---

package.json
src/add-hooks.js
test/mocha.opts

It just remove a warning at dredd installation : `warning dredd > coffee-script@1.12.6: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)`

CoffeeScript on NPM has moved to "coffeescript"

---

src/reporters/html-reporter.js
src/reporters/markdown-reporter.js

Both the html and markdown reporters are currently broken with `TypeError: Cannot read property 'level' of undefined at title`.
This is caused by a faulty coffeescript conversion where a fat arrow function was converted to a regular function without taking into effect that `@level`/`this.level` would then be broken.
Using an arrow functions brings back the old behavior.
-

fix(reporters): Use correct context after faulty CoffeeScript conversion

---

package.json

Let's support the latest old CoffeeScript in the Dredd hooks. In the future, CoffeeScript should be removed from dependencies completely in favor of a different ways how to use transpiled languages in the hooks.

Update coffeescript to the latest of the 1.x.x series

---

src/configuration.js
test/integration/cli/cli-test.js

The `Buffer` constructor is deprecated (it will likely start throwing warnings in Node.js 10), instead `Buffer.{from|alloc|allocUnsafe}` should be used. 
Discussion of the API change: https://medium.com/@jasnell/node-js-buffer-api-changes-3c21f1048f97
Runtime deprecation planning: nodejs/node#19079
This is also preparation for #975.

chore: Don't use the deprecated Buffer constructor

---

package.json
test/unit/dredd-command-test.js

Merely staying up to date for deduplication. The breaking changes are not relevant to dredd itself but a test needed fixing.

chore: Update proxyquire to version 2

---

package.json

This release removed use of the deprecated Buffer constructor and will prevent a warning on Node.js 10.
- See #979 for removal of the use of the constructor in dredd itself
- moxystudio/node-cross-spawn#94

fix: Update cross-spawn to 6.0.5

---

docs/hooks.md

Rust is supported for a long time already, but it's missing in this particular list.

Add Rust to the list

---

docs/data-structures.md

Fix moved link

---

docs/usage-js.md
scripts/semantic-release.sh
test/mocha.opts

Slowly getting rid of some of the remaining references to coffeescript. This is just the first PR but the desired end result should be that it's only used for coffeescript hooks and nothing else.

Remove some more usage of coffeescript

---

docs/installation.md
docs/quickstart.md

The sections are either misleading or not relevant anymore.

Clean up Windows docs

---

docs/hooks-nodejs.md

Shows an example for multi-part formdata requests modification on before hooks.
Closes https://github.com/apiaryio/dredd/pull/1015, an awesome contribution by @sajjad-shirazy. The commit here keeps his authorship. I'm only fixing commit message length, as otherwise the commit message linter gets upset 🙄

Add example of modifying multipart request body

---

package.json

There has been a security report for `stringstream` which is a dependency of the current `request` version: https://nodesecurity.io/advisories/664. 
The issue will probably not affect this issue, but it's nice to remove vulnerable packages from the tree.
npm audit report:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Out-of-bounds Read                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ stringstream                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │ …
```

fix: Update request

---

test/unit/hooks-worker-client-test.js

Flaky tests are no fun 👎 
Closes https://github.com/apiaryio/dredd/issues/804

Fix flaky "methods dealing with connection to the handler are stubbed" suite in hooks-worker-client-test.js

---

package.json
test/integration/response-test.js

The upgrade brings fixes in draft3 JSON Schema validation. Solves a problem with date time validation reported by @erajkovic.

Upgrade Gavel.js

---

test/integration/cli/cli-test.js

_"...when using language hook handler and spawning the server and handler is killed before execution should return with status 1"_ test is currently killing our builds on Windows, let's skip it until it is fixed.
https://github.com/apiaryio/dredd/issues/1030

Skip flaky CLI test

---

src/dredd-command.js
test/integration/cli/cli-test.js

Flaky test ain't fun 👎 
Fixes #1030

Fix flaky cli-test.js test case on Windows

---

docs/hooks-php.md

Documentation fix -- example should show variable in parent scope passed by reference.
N/A

docs: Fixing php hooks doc.

---

package.json

IMHO nobody uses this anyway. Semantic Release prefixes need to be enforced on CI level and reminded in Pull Requests. I think the commitizen config doesn't really help to solve any real issues and moreover it has some licensing issues.
Close https://github.com/apiaryio/dredd/issues/1049

Remove commitizen

---

src/child-process.js
src/common.js
src/dredd-command.js
src/ignore-pipe-errors.js

Flaky test ain't fun 👎, round two.
Fixes #1030

Fix flaky cli-test.js test case on Windows, round two

---

.github/CONTRIBUTING.md
.travis.yml
README.md
docs/conf.py
docs/data-structures.md
docs/hooks-nodejs.md
docs/how-it-works.md
docs/index.md
docs/installation.md
docs/requirements.txt
package.json

Reverts #829. Since we have migrated the docs to Sphinx, there has been a plan to lint the docs and to build them on Travis CI as well to verify under Pull Requests that the docs can be built and there are no broken links.
This was implemented, but had to be removed as it wasn't possible to make it working on Travis CI with `nodejs` builds and Python 3. Now we're on `trusty` and it should be all good.
- follow-up to #829
- includes a workaround to https://github.com/sphinx-doc/sphinx/pull/5140/
- closes https://github.com/apiaryio/dredd/issues/610 (checker of broken links)
- closes https://github.com/apiaryio/dredd/issues/551

Lint docs and build them on Travis CI

---

package-lock.json
package.json
src/hooks-worker-client.js
src/reporters/apiary-reporter.js

Quick bump for uuid to keep deduplication with request.

Update uuid to 3.3.2

---

.github/CONTRIBUTING.md

It's better and now it's even possible!
https://github.com/rtfd/readthedocs.org/issues/328

Use HTTPS in the docs shortened link

---

package-lock.json
package.json

As described in https://github.com/apiaryio/dredd/issues/1088, `mocha@<4` has security vulnerability via its `growl` dependency. There was a breaking change in `mocha@4.0.0` that caused Windows test to run indefinitely - adding `--exit` flag fixes the issue.
Closes https://github.com/apiaryio/dredd/issues/1088

Upgrade mocha to 5.2.0

---

.github/CONTRIBUTING.md

Fix filename

---

.eslintrc.js

Unlike other exceptions in ESLint config, which are to be treated as outstanding bugs to resolve, we decided we won't ever want to turn this one on. This PR documents the decision.
- https://github.com/apiaryio/dredd-transactions/pull/179#discussion_r206852270
- https://github.com/apiaryio/dredd/pull/1094#discussion_r206821763

Document why no-underscore-dangle is off

---

.travis.yml

The https://github.com/apiaryio/dredd/pull/1110 fixed a vulnerability in Dredd's dependencies, but we did not classify the commits as a fix and thus it did not get released, leaving the latest Dredd version still vulnerable.
https://github.com/apiaryio/dredd/pull/1110, #1107

Release a vulnerability fix

---

docs/conf.py
docs/how-it-works.rst
docs/how-to-guides.rst

`master` Travis CI build is failing.
- https://github.com/apiaryio/dredd/pull/1119
- https://github.com/apiaryio/dredd/pull/1122

Fix master

---

.travis.yml
docs/conf.py
docs/extensions/cli_options.py
docs/extensions/ghissue.py
docs/how-it-works.rst
docs/how-to-guides.rst
package.json

It simplifies the markup when referencing GitHub issues. Tiny little Friday task.

Add :ghissue: role to Sphinx

---

docs/internals.rst

We now have an extension to simplify such things.
https://github.com/apiaryio/dredd/pull/1127

docs: use the new :ghissue: role

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
docs/how-to-guides.rst
docs/index.rst
docs/internals.rst
src/dredd.js
src/reporters/apiary-reporter.js
test/integration/dredd-test.js

We have dredd.org, we should use it! Also, with this we won't rely on ReadTheDocs that much in the future.

Use https://dredd.org as the canonical URL

---

package-lock.json
package.json

There are several vulnerabilities in the dev dependencies we haven't updated for a while. This mitigates the ones introduced through `coveralls`
- Mitigate medium severity vulnerability https://snyk.io/vuln/npm:cryptiles:20180710
- Mitigate medium severity vulnerability https://snyk.io/vuln/npm:tunnel-agent:20170305
- Mitigate low severity vulnerability https://snyk.io/vuln/npm:hoek:20180212
- Close https://github.com/apiaryio/dredd/issues/1050

Mitigate the latest vulnerabilities in dev deps (coveralls)

---

docs/conf.py

It makes the build longer for no reason.

Don't install optional deps on RTD

---

README.md
docs/index.rst
docs/quickstart.rst

I was way too brutal in wiping out Swagger from the Dredd docs 😄 Originally I wanted to mention that OpenAPI 2 was formerly called Swagger so people are not confused and it shows up in search results correctly: https://github.com/apiaryio/dredd/issues/994#issuecomment-419152889 
- https://github.com/apiaryio/dredd/issues/994
- https://github.com/apiaryio/dredd/pull/1133
- https://github.com/apiaryio/dredd/pull/950#issuecomment-358544305

Mention Swagger

---

docs/quickstart.rst

This is the canonical link to the dredd-test-rails repository.

Fix link to dredd-test-rails source

---

.travis.yml
package.json
scripts/coveralls.sh
scripts/smoke.sh

I want to fiddle with how Dredd is built and packaged. From my very own experience, in 99% cases this leads to silly mistakes breaking the installability of the resulting package (discrepancies in `.npmignore` and `.gitignore`, wrong Babel setting, etc.). For this reason https://github.com/apiaryio/dredd/issues/528 was filed and the aim of this PR is to implement the proposed smoke test using an additional Travis CI job.
- Close https://github.com/apiaryio/dredd/issues/528

Introduce smoke tests

---

test/integration/cli/reporters-cli-test.js

I was wondering why testing locally produces the `__test_directory` on my machine and figured out one of the tests uses this directory and it does not clean it properly. I never noticed it as empty directories do not get to Git and since this one started with `__`, it appeared at the top of my file explorer in my editor, which is apparently my blind spot.
Note the test is ugly and the directory should be a temporary directory, but that's a mission for future generations, this is a hotfix PR.

Remove test directory after the test

---

README.md
docs/index.rst

I didn't know https://readthedocs.org/projects/dredd/builds/ is actually accessible publicly, but it seems so from anonymous browser window. It is a better link to have there as when the badge is red, it leads to a place where to resolve the problem.

Fix link to docs builds

---

.eslintignore

Running ESlint locally catches a lot of files which it shouldn't catch.

Improve ESLint ignores

---

scripts/postshrinkwrap.js

There is a typo (article) and when fixing it, I decided to use nicer language.
- https://github.com/apiaryio/dredd/pull/1168

Use different language in the script comment

---

npm-shrinkwrap.json
scripts/postshrinkwrap.js

Because I want to prevent PRs like https://github.com/apiaryio/dredd/pull/1170 regardless of any npm / shrinkwrap / lockfile quirks and workflows.
https://github.com/apiaryio/dredd/pull/1170

Never have dev deps in shrinkwrap

---

.eslintrc.js
lib/childProcess.js
lib/configUtils.js
lib/reporters/ApiaryReporter.js
lib/reporters/BaseReporter.js
lib/reporters/CLIReporter.js
lib/reporters/DotReporter.js
lib/reporters/HTMLReporter.js
lib/reporters/MarkdownReporter.js
lib/reporters/NyanReporter.js
lib/reporters/XUnitReporter.js
test/integration/childProcess-test.js
test/integration/cli/hookfiles-cli-test.js
test/integration/helpers.js
test/integration/regressions/regression-319-354-test.js
test/reporter.js
test/unit/configureReporters-test.js
test/unit/reporters/ApiaryReporter-test.js

I want to get rid of ESLint exceptions if possible. The changes made to reporters are debatable. The reporters should be probably rewritten to the `class` syntax. However, the ideal plan is to revamp them from the ground up, so I don't want to invest my time in them that much now.

Require named function expressions

---

docs/hooks/go.rst
docs/hooks/index.rst
docs/hooks/perl.rst
docs/hooks/php.rst
docs/hooks/python.rst
docs/hooks/ruby.rst
docs/hooks/rust.rst
docs/installation.rst

Using Dredd inside Docker isn't as simple as it seems at first sight.
- Needs rebase when https://github.com/apiaryio/dredd/pull/1181 is merged
- Closes apiaryio/docker-base-images#149
- Closes #748 
- Documents #755

Improve Docker docs

---

docs/conf.py
docs/internals.rst

We're getting failed docs builds recently, because the npm in RTD's image isn't able to install npm dependencies successfully - see https://readthedocs.org/projects/dredd/builds/8343339/ To my surprise, the latest RTD image contains node@4.2.6 and npm@3.5.2. This means not only that it might be a bug in the npm, which is could be already fixed in newer versions, but also that the obvious quick solutions, such as 'npm ci' or using 'npx', are not available. This brought me to revisiting why we install npm dependencies in the first place. In the past the docs had node extensions, but now the only thing needing the dependencies was the version number, calling semantic-release. I decided to hardcode the version to 'latest' to avoid the issues and to remove the complexity.
- …

Hardcode the version to 'latest' in the docs

---

package.json

After recent renaming of files to conform to JS Airbnb style guide, we forgot to change `package.json` as well.
Fix https://github.com/apiaryio/dredd/issues/1187

Fix the JS API path for case-sensitive systems

---

docs/hooks/js-sandbox.rst
lib/addHooks.js

Puts https://github.com/apiaryio/dredd/issues/1178 in action. Small step for Dredd users, big step for Dredd's codebase!
- https://github.com/apiaryio/dredd/issues/1178

Announce sandboxed JS hooks as deprecated

---

lib/configuration.js
scripts/smoke.sh

Fixes https://github.com/apiaryio/dredd/issues/1189
Prevents https://github.com/apiaryio/dredd/issues/1187

Add minimal test of Dredd's JS API

---

docs/internals.rst

Follow-up to https://github.com/apiaryio/dredd/pull/1082

Remove a sentence about CoffeeScript from Internals docs

---

README.md
docs/index.rst
package.json

Because we want to support OAS3 😄 
Closes https://github.com/apiaryio/dredd/issues/894

Add experimental OpenAPI 3 support

---

README.md

Added the url to the read me for OpenAPI v3.
The link to the version 3.0 readme was missing. 
None
Quick readme fix, so not sure any of these are applicable, but if they are, Ill absolutely fix.

Update readme to add link for OpenAPI v3

---

test/integration/cli/api-blueprint-cli-test.js
test/integration/cli/api-description-cli-test.js
test/integration/cli/openapi2-cli-test.js
test/integration/cli/reporters-cli-test.js
test/integration/cli/server-process-cli-test.js
test/integration/dredd-test.js
test/integration/helpers.js
test/integration/proxy-test.js
test/integration/regressions/regression-319-354-test.js
test/integration/require-test.js
test/integration/sanitation-test.js
test/unit/CLI-test.js
test/unit/Hooks-test.js
test/unit/addHooks-test.js
test/unit/getGoBinary-test.js

In the pursuit of extreme test isolation, the test suite is extremely slow compared to what's in there. Sure, integration tests with process spawning etc. are destined to be slow, but otherwise there's a lot of room for improvement if we agree `beforeEach()` really isn't needed everywhere.
------------
Before:
After:
Close https://github.com/apiaryio/dredd/issues/1217

Speedup tests

---

bin/dredd
package.json

Ensure that bin/dredd conforms to style guide

---

lib/options.json

I opened the file and it was hard to read.
Nupe.

Fix JSON syntax in options to be consistent

---

lib/Dredd.js
package.json
test/unit/Dredd-test.js
test/unit/handleRuntimeProblems-test.js

Depends on https://github.com/apiaryio/dredd/pull/1258
-------
This upgrades Dredd Transactions and uses their new public interface. The `compileTransactions` function is a mess, but refactoring that is a challenge for another day.

Upgrade Dredd Transactions to v7

---

docs/data-structures.rst
docs/usage-js.rst
lib/Dredd.js
lib/TransactionRunner.js
lib/configuration.js
lib/handleRuntimeProblems.js
lib/reporters/ApiaryReporter.js
lib/reporters/BaseReporter.js
lib/reporters/CLIReporter.js
lib/reporters/DotReporter.js
lib/reporters/HTMLReporter.js
lib/reporters/MarkdownReporter.js
lib/reporters/NyanReporter.js
lib/reporters/XUnitReporter.js
test/fixtures/apiDescriptions.js
test/integration/annotations-test.js
test/integration/sanitation-test.js
test/unit/Dredd-test.js
test/unit/configuration-test.js
test/unit/handleRuntimeProblems-test.js
test/unit/reporters/ApiaryReporter-test.js
test/unit/transactionRunner-test.js

Depends on https://github.com/apiaryio/dredd/pull/1259
---------
This is a beginning of a larger refactoring, which will allow for simpler code at various places.
- Introducing `apiDescriptionMediaType` as part of the transaction object allows to remove a fragile dependency on the `configuration` object in `configureTransaction` inside the transaction runner
- The `apiDescriptions` name makes more sense to me than `data`, the docs and the configuration has been adjusted accordingly
- The configuration _is_ a mess, the tests _are_ ugly, but those are challenges for another day
- The `.includes('swagger')` doesn't scale, but will be addressed separately - https://github.com/apiaryio/dredd/issues/1257

Rename 'configuraton.data' to 'configuration.apiDescriptions'

---

lib/init.js
test/unit/init/applyAnswers-test.js

Aims to set a proper value for the `language` key in the generated `dredd.yml` after running the following command:
```bash
dredd init
```
Please refer to the mentioned GitHub issue for the reproduction steps.
- Fixes #1239

fix: (dredd.yml) Uses default "language" value when not prompted

---

docs/hooks/go.rst

fix(documentation): invalid struct field in go hooks example

---

lib/Dredd.js
lib/HooksWorkerClient.js
lib/addHooks.js
lib/configuration.js
lib/resolveHookfiles.js
lib/resolveLocations.js
lib/resolvePaths.js
test/integration/cli/api-description-cli-test.js
test/unit/Dredd-test.js
test/unit/addHooks-test.js
test/unit/resolveHookfiles-test.js
test/unit/resolveLocations-test.js
test/unit/resolvePaths-test.js
test/unit/transactionRunner-test.js

Dredd now resolves globs for both hookfiles and API descriptions paths. The logic of resolving them is the same, so I think the code taking care of it should be the same as well.

Use the same code for resolving globs in paths

---

lib/Dredd.js
lib/configureReporters.js
lib/reporters/ApiaryReporter.js
lib/reporters/BaseReporter.js
lib/reporters/CLIReporter.js
lib/reporters/DotReporter.js
lib/reporters/HTMLReporter.js
lib/reporters/MarkdownReporter.js
lib/reporters/NyanReporter.js
lib/reporters/XUnitReporter.js
test/unit/Dredd-test.js
test/unit/configureReporters-test.js
test/unit/reporters/ApiaryReporter-test.js
test/unit/reporters/BaseReporter-test.js
test/unit/reporters/CLIReporter-test.js
test/unit/reporters/DotReporter-test.js
test/unit/reporters/HTMLReporter-test.js
test/unit/reporters/MarkdownReporter-test.js
test/unit/reporters/NyanReporter-test.js
test/unit/reporters/XUnitReporter-test.js

The `this.tests` structure in Dredd.js is unused and unnecessary. This PR removes it from the codebase and all interfaces, mainly the reporters.
The change is a part of cleaning up Dredd class'es constructor, and there are also two additional changes. The reporters get configured and the proxy settings get logged in the `.run()` method, to keep the constructor without side effects. I had to fix Dredd.js unit tests because of that.
Factored out from https://github.com/apiaryio/dredd/pull/1289

Remove redundant 'tests' structure

---

lib/CLI.js
lib/Dredd.js

Streamlining how the codebase is written.
Factored out from https://github.com/apiaryio/dredd/pull/1289/

Require options where they're used

---

lib/reporters/HTMLReporter.js

Adds a summary section to the HTMLReporter output.
* Fixes #1001

HTMLReporter: Add summary

---

lib/performRequest.js

Because I think `response` is better than `res`.
Factored out from https://github.com/apiaryio/dredd/pull/1289/

Use explicit variable names

---

lib/Dredd.js
lib/TransactionRunner.js
test/unit/Dredd-test.js

The `emitStart` and `emitEnd` methods were originally part of Dredd.js, but I moved them to the transaction runner. All other events are emitted in the transaction runner, so I thought it's a good idea to streamline the concerns of the components.
I didn't rewrite the code, only moved it around and indented what was necessary. The result is not meant to be beautiful at this stage.
Factored out from https://github.com/apiaryio/dredd/pull/1289/

Move events from Dredd.js to the Transaction Runner

---

docs/installation.rst

Encountered some issues testing a service running on host from a Dredd Docker image.

Add a note about docker to host networking

---

docs/internals.rst

The list was incomplete, `style:` was missing. I also sorted the prefixes according to their impact and added some more comments at various places.

Update the list of conventional changelog prefixes

---

.gitignore

Not to accidentally commit `__pycache__` directories.

Ignore __pycache__ directories

---

lib/TransactionRunner.js

Introduces an explicit list of validation result sections to be present in the Dredd's transaction runner output. This allows Dredd to be independent from Gavel's validation order, and also makes it resilient to new Gavel releases.
- Fixes #1371

fix: uses explicit validation result sections list for logging output

---

test/integration/sanitation-test.js

Uses `hasAllKeys` for assertion of validation results object keys in sanitization tests. Makes assertion order-insensitive, improving the tests' sustainability. Also fixes a logical flaw where object's keys are asserted in specific order.
- Fixes #1368

test: uses "hasAllKeys" for order-insensitive keys assertion

---

lib/configuration/applyConfiguration.js
lib/configuration/normalizeConfig.js
test/integration/configuration/resolveConfig-test.js

- Moves coercion of `server` option from `flattenConfig` to `normalizeConfig`
- Explicitly checks `R.has('server')` to prevent erazing the value of `endpoint`, which acts as a target of the value coercion
- Fixes #1370

fix: coerces "server" option to "endpoint"

---

lib/addHooks.js
test/unit/addHooks-test.js

I believe it is a regression. @kylef had to work around it when upgrading Dredd in https://github.com/apiaryio/polls-api/pull/66/commits/4f66c3409757f241334473ed2d13fba0f5c7142a
- https://github.com/apiaryio/polls-api/pull/66

Do not initiate hooks if there are no hookfiles

---

lib/TransactionRunner.js
package.json
test/integration/sanitation-test.js

- Removes [deprecated `gavel.isValid(https://github.com/apiaryio/gavel.js/issues/166)` method]() usage from Dredd.
- Consequentially, improves performance by validating transaction once, as opposed to twice previously (`gavel.isValid()` used to validate a transaction, but share no results with you).
- Changes are a part of Gavel upgrades and have no corresponding Dredd issue I'm aware of

feat: removes "gavel.isValid" calls

---

lib/CLI.js

To fix dredd.yml config usage
https://github.com/apiaryio/dredd/issues/1377

fix: using "apiaryApiKey" and "apiaryApiName" from dredd.yml config

---

docs/index.rst
docs/internals.rst

We use other tools now to monitor dependencies and the links to David stopped to work.

docs: remove david dm

---

.travis.yml

Current Travis CI build fails due to inability to run `pyenv global 3.6`. The mentioned version doesn't appear to be properly installed (most likely for a third-party reason). This pull request installs an explicit `pyenv` version and uses it throughout the build.
- Fixes #1448

Installs "python@3.6" explicitly during the build

---

docs/data-structures.rst
docs/internals.rst

- Some of the documentation links still point to the removed `ApiaryReportingAnonymous.apib` file. They must be updated.
- Fixes #1472

docs: removes links to "ApiaryReportingAnonymous.apib"

---

docs/_extensions/ghlink_check.py
docs/conf.py

It can happen that a file, which is linked by an absolute GitHub link from the docs, is removed from a development branch. Such link passes as not broken with the existing link check, but when a PR with such branch gets merged into master, the file disappears and the link gets broken (and master build gets broken). This commit introduces a simple extension to prevent that.
https://github.com/apiaryio/dredd/issues/1472

Add extension for detecting broken links to Dredd's repository

---

lib/TransactionRunner.js
test/unit/transactionRunner-test.js

Fixes an empty `resultData.results` sent to the Apiary Reporter when a test has been skipped.
- https://github.com/apiaryio/apiary/pull/6267

fix: ensures skipped test inherits transaction data

---

.dependabot/config.yml

Because https://github.com/apiaryio/dredd/releases/tag/v12.0.1

Fix the prefix, py deps are used only for docs

---

lib/Dredd.js
lib/Hooks.js

- Certain parts look like survivors after decaffeinate, and represent invalid JavaScript code
- Necessary prerequisite for #1524 
- Problematic spots found in #1497

Fixes syntactically invalid JavaScript

---

appveyor.yml

We always use the latest Node version we support when testing on AppVeyor. We added Node 12 to the other CI, but didn't switch AppVeyor to use it.

Use Node 12 in AppVeyor

---

docs/internals.rst

I recently added an extension to Sphinx, but I forgot to document it.

Document GitHub links checker extension

---

docs/redirects.yml

All langs but Rust have redirects set up. Without redirect, the link specified in README.md not going to work, so adding missing conf
To fix [Rust link in README](https://github.com/apiaryio/dredd/blob/master/README.md#supported-hooks-languages), which is currently 404

docs: fix Rust hooks link

---

packages/dredd-transactions/.gitignore
packages/dredd-transactions/package.json
packages/dredd-transactions/scripts/postpack.js
packages/dredd-transactions/scripts/prepack.js

This improves the hack which gets rid of protagonist (i.e. C++ compilation of drafter, the API Blueprint parser). When we moved dredd-transactions to the monorepo, where dependencies are managed by yarn workspaces, the hack to get rid of protagonist stopped to work. The hack relies on 'bundledDependencies', but those stopped to work. 'npm pack' cannot find the dependencies to bundle if they're in the root 'node_modules' directory. 'yarn pack' doesn't work either, it has bugs and it doesn't support 'bundledDependencies' or the workspaces very well - see https://github.com/yarnpkg/yarn/issues/6794
This change overcomes the limitation by improving the prepack.js script. It now iterates over the 'bundledDependencies' and symlinks them to the local 'node_modules' directory where 'npm pack' can …

Fix dependencies bundling for yarn workspaces

---

packages/dredd/package.json

Removes `test:debug` command which is not used and is not a valid command.
Instead, it's preferred to use:
```bash
$ npm test -- --grep="sanitation"
$ npm test -- --inspect-brk
```
- Relates to #1393

chore: removes "test:debug" script

---

packages/dredd/package.json
yarn.lock

Because I f***ed up by merging a PR with semantic release upgrade and now we have a merge conflict on https://github.com/apiaryio/dredd/pull/1551. I hope this could remove the conflict and make the PR mergeable again.
- https://github.com/apiaryio/dredd/pull/1551
- https://github.com/apiaryio/dredd/pull/1566

Remove semantic release

---

docs/how-to-guides.rst
packages/dredd/ApiaryReportingApi.apib
packages/dredd/lib/reporters/ApiaryReporter.js
packages/dredd/test/integration/apiary-reporter-test.js
packages/dredd/test/integration/cli/reporters-cli-test.js

Changes the phrasing from "API Project Subdomain" to "API Project Name" to make the expectations more obvious. 
- Closes #611

Uses "API Project Name" term over "API Project Subdomain"

---

packages/dredd/package.json
yarn.lock

These dependencies have been introduced but then never used. They should be removed. Please do https://github.com/apiaryio/dredd/pull/1551 with priority.
If this PR then gets a merge conflict, it can be re-done copy-pasting this:
```
$ git checkout master && git pull origin master && git checkout -b shared/remove-rollup && npx lerna clean && yarn && cd packages/dredd && yarn remove rollup rollup-plugin-commonjs rollup-plugin-json rollup-plugin-node-externals rollup-plugin-node-resolve rollup-plugin-typescript2
```

Remove unused dependencies

---

packages/dredd/lib/general.ts
packages/dredd/lib/sortTransactions.ts
packages/dredd/options.json
packages/dredd/test/unit/sortTransactions-test.ts

Adds missing `LINK` and `UNLINK` HTTP methods to abide by the `--sorted` CLI flag. Sets them in the expected order in correspondence to other methods and provides unit tests.
- Fixes #267

Adds "LINK" and "UNLINK" HTTP methods

---

docs/how-it-works.rst
packages/dredd/package.json
packages/dredd/test/fixtures/json-schema-draft-7-boolean.apib
packages/dredd/test/fixtures/json-schema-draft-7.apib
packages/dredd/test/integration/json-schema-draft-7-test.js
yarn.lock

> **Currently Dredd release is blocked by https://github.com/lerna/lerna/pull/2358**
- To support JSON Schema Draft 6/7 validation in Dredd
- Gavel implementation https://github.com/apiaryio/gavel.js/pull/355

Updates Gavel for JSON Schema Draft 6/7 support

---

.circleci/config.yml

- Latest CircleCI images already have Yarn installed. Attempts to install it again break the build.
- https://github.com/apiaryio/api-elements.js/pull/395

Skips yarn installation on the latest circleci images

---

packages/dredd/test/fixtures/531-produces-consumes.yaml
packages/dredd/test/integration/regressions/regression-531-test.js

Adds missing integration test for OA2 `produces`/`consumes` properties. 
- Closes #531

test: adds OA2 produces/consumes integration test

---

packages/dredd-transactions/package.json
yarn.lock

- The newest versions of `fury-adapter-oas3-parser` and `fury-adapter-swagger` contain fixes for issues reported in Dredd
> The issues that are related to these changes must be verified once this pull request lands. There is a solid chance they will be resolved after these changes.
- Related to #1647  (should be closed when Gavel uses AJV for JSD4)
- Related to #1218
- Related to #1329
- Related to #1116
- Related to #1111

Updates "fury-adapter-oas3-parser" and "fury-adapter-swagger"

---

docs/_links.rst
docs/how-it-works.rst
packages/dredd/package.json
packages/dredd/test/fixtures/schema.apib
packages/dredd/test/integration/cli/hookfiles-cli-test.js
yarn.lock

- To include the latest version of Gavel that removes JSON Schema Draft 3 support
- No related issues, governance task

chore(deps): bumps "gavel" to "9.1.1"

---

packages/dredd-transactions/package.json
yarn.lock

- To keep dependencies up-to-date
- No related task, governance

fix: bumps "fury-adapter-swagger" to 0.28.2

---

docs/hooks/ruby.rst

Fix compilation error (`do` -> `end`) and missing `require` statements
N/A

docs: Fix Ruby.rst code examples

---

packages/dredd-transactions/package.json
packages/dredd/package.json

The main changes for this release are to update fury-adapter-oas3-parser which incorporates changes to support the explode modifier in OpenAPI 3 query parameters.
This should solve https://github.com/apiaryio/dredd/issues/1737.

Release dredd 13.1.1

---

packages/dredd-transactions/compile/index.js
packages/dredd-transactions/package.json
packages/dredd/package.json
yarn.lock

This brings fixes for the OpenAPI 2 and 3 parsers, namely a fix for https://github.com/apiaryio/dredd/issues/1686

Update OpenAPI 2/3 parsers and release

---

docs/installation.rst

Fixes failing quality checks because of documentation link of npmjs configuration was changed.
`tests` automation will be unblocked in almost all PRs thanks to this little change.

docs(installation): fix link to npmjs' https-proxy config

---

packages/dredd/package.json

- updated request 2.88.0 to 2.88.2
- updated node-fetch 2.6.0 to 2.6.1
- updated @types/ramda 0.27.4 to 0.27.32
- updated js-yaml 3.13.1 to 3.14.0.

chore: bump dredd version to 13.2.0

---

.circleci/config.yml
.github/workflows/run-test.yml
package.json
packages/dredd-transactions/package.json
packages/dredd/package.json
yarn.lock

Remove 4th party deps security vulnerabilities:
* `dot-prop < 2`
* `lodash < 4.17.20`
* `kind-of >= 6.0.0, < 6.0.3`
Drops node v8.x support (the upgraded dependencies stopped supporting it).

chore: upgrade devDependencies, drop node v8.x support

---

packages/dredd-transactions/package.json
packages/dredd/package.json

- Removes NodeJS@8 support (EOL).
- Updates dependencies (incl. security issues fixes).

chore: bump dredd version to 14.0.0

---

docs/hooks/new-language.rst

```
Warning, treated as error:
/Users/abtris/Sites/apiaryio/dredd/docs/hooks/new-language.rst.rst:11:broken link: hall-of-fame ()
error Command failed with exit code 2.
```
#1883

docs: fix broken link: hall-of-fame

---

packages/dredd/lib/HooksWorkerClient.js
packages/dredd/lib/reporters/ApiaryReporter.js

when i run `dredd` command , my terminal show 
```
(node:11604) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.
```
this PR just update uuid deprecated

fix(deps): update uuid deprecated

---

packages/dredd-transactions/package.json
yarn.lock

This updates numerous dependencies which bring new Dredd features by the way of the changed in OpenAPI 3 Parser. This will close the related issues below because there is initial support for schema found within Parameter Object's
- https://github.com/apiaryio/dredd/issues/1363
- https://github.com/apiaryio/dredd/issues/1785

Update @apielements toolchain

---

commitlint.config.js

```
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
✖   body's lines must not be longer than 100 characters [body-max-line-lengt
```
#1929

chore(test): fix for too long messages with links

---

packages/dredd/lib/init.js

Errors updating Travis CI configuration files were neither logged nor raised to indicate a problem occurred. Instead, Dredd silently failed without creating a `.dredd.yml` file.
Fixes #1964 
No unit tests added or modified as part of this change. If reviewers believe this change warrants unit test(s), let me know and I'll be happy to revisit.

fix: capture and log ci update errors

---

.github/workflows/run-docs-test.yml
docs/conf.py
docs/requirements.txt

```
Error : .github#L1
wagoid/commitlint-github-action@v2 is not allowed to be used in apiaryio/dredd. Actions in this workflow must be: within a repository that belongs to your Enterprise account
```
Tests doesn't run.

fix: non-approved GH action

---

packages/dredd-transactions/scripts/postpack.js
packages/dredd-transactions/scripts/prepack.js

Adds logs to the said scripts so it's easier to debug issues occurring during the publishing process. 
I just had an issue where the `dredd-transactions/node_modules/protagonist` symlink already existed. It threw an exception when trying to create the link again. It also appears that `fs.existsSync` always returns `false` for symlinks (needs verification). We may consider using `fs.readlinkSync` instead to check if the symlink exists (careful, though, as `readlinkSync` throws when it doesn't).

chore: add logs to "prepack" and "postpack" scripts

---

CONTRIBUTING.md
README.md
RELEASE.md
commitlint.config.js

1. There was room for improvement in the Contributing guide for "Improving Dredd": additional steps to document along with a suggested change in ordering, and
2. local Markdown linting tools also suggested formatting improvements between the Contributing, Readme, and Release docs.
These changes were originally incorporated into PR #1965 for issue #1964.
No unit tests added or modified as part of this change - documentation amendments only.

docs: improve contributing steps with formatting clean up
