apiaryio/dredd

- .travis.yml
- package.json
- test/integration/cli-test.coffee
- also update hipchat notification
- use http://docs.travis-ci.com/user/workers/container-based-infrastructure/
- update travis to install `npm@1.4.x`
> Fix cli-test by freezing devDependency clone@0.x

- package.json
- src/dredd.coffee
- test/unit/dredd-test.coffee
> Allow to pass config data directly - via "directInput" object

- README.md
- bin/dredd
- package.json
- src/dredd.coffee
- src/options.coffee
- test/integration/cli-test.coffee
> Load blueprint-file from provided URL from http/https

- test/unit/dredd-test.coffee
> Add unit tests when path is a URL to blueprint file

- .gitignore
- src/add-hooks.coffee
- src/apply-configuration.coffee
- src/configure-reporters.coffee
- src/dredd.coffee
- src/reporters/apiary-reporter.coffee
- src/reporters/dot-reporter.coffee
- src/reporters/nyan-reporter.coffee
- src/transaction-runner.coffee
- test/integration/cli-test.coffee
- test/unit/apply-configuration-test.coffee
- typos
- leftovers (bad variables, remnants of the past)
- whitespace
- small minor details with no large™ impact (move reusable functions out of scopes)
> Various small fixes

- src/add-hooks.coffee
- src/transaction-runner.coffee
- test/fixtures/regression-152.coffee
- test/regressions/regression-152-test.coffee
- test/unit/transaction-runner-test.coffee
- fixes #152 
- adds a test for regressions
- also adds an explanation of why did that happened
> Hooks loosing context / reference to transaction because async.eachSeries

- README.md
- docs/hooks.md
- docs/transaction.md
- also add links to Gavel, ISO and NodeJS
> Fix small typos in documentation

- src/add-hooks.coffee
- src/hooks.coffee
- src/transaction-runner.coffee
- test/unit/add-hooks-test.coffee
- test/unit/hooks-test.coffee
- test/unit/transaction-runner-test.coffee
- this allows to actually use Dredd via JS interface multiple-times at the same moment
> One Hooks instance per one Dredd instance

- README.md
- package.json
- src/dredd-command.coffee
- src/dredd.coffee
- src/interactive-config.coffee
- test/integration/cli-test.coffee
- test/unit/dredd-command-test.coffee
- disabled Apiary test reporter configuration
- fixed passing of additional arguments when dredd.yml present
- fixed README formatting
> Dredd init fix

- .gitignore
- .npmignore
- CHANGELOG.md
- docs/example.md
- docs/overview.md
- package.json
Start writing Changelog, with little help from `github-changes` npm package
closes #208
> Changelog origin

- docs/hooks.md
- src/hooks.coffee
- src/transaction-runner.coffee
- test/unit/dredd-test.coffee
- test/unit/transaction-runner-test.coffee
These hooks fire after Dredd has received a response from the server, but before it is handed off to gavel. If you need to make modifications to the response before validation, these are the hooks for you.
> New hooks: `beforeValidation` and `beforeEachValidation`. Fixes #221

- src/transaction-runner.coffee
- test/unit/transaction-runner-test.coffee
> Clean beforeResults for every gavelResult iteration

- test/fixtures/python-hooks/dredd.py
- test/fixtures/python-hooks/hooks-worker-client.coffee
- test/integration/cli-test.coffee
Python worker test - based on the ruby worker, it's basically 1to1 copy
> Python hooks test

- README.md
- docs/canonical-paths.md
- docs/example.md
- docs/hooks-nodejs.md
- docs/hooks-python.md
- docs/hooks-ruby.md
- docs/hooks.md
- docs/index.md
- docs/overview.md
- docs/quickstart.md
- docs/usage.md
- src/options.coffee
- Fixed typos, links and so in docs
- example code in python to be more pythonic
> docs review and fixes

- src/hooks-worker-client.coffee
- test/unit/hooks-worker-client-test.coffee
`hadnler` and `transacition` are the words :)
> Typos all the way

- README.md
- docs/index.md
Mostly to make it look better when using a retina device.
Before:
After:
> Use vector badges in the README

- docs/overview.md
I wrote a Dredd integration for [Meteor](https://github.com/meteor/meteor). I wondered if you might want to add it to the known list of Dredd eco-system integrations.
> Dredd + Meteor for known eco-system integrations

- docs/example.md
- docs/hooks-new-language.md
- docs/hooks-php.md
- docs/hooks.md
- docs/index.md
I have a working implementation of dredd hooks in PHP at this [repository](https://github.com/ddelnano/dredd-hooks-php).  I added it to the Dredd documentation so others can be aware of it, now that it is a stable release.
> Added dredd-hooks-php to documentation 

- docs/index.md
> Fix spelling mistake on index.md

- docs/hooks-go.md
- docs/hooks-new-language.md
- docs/hooks.md
- docs/index.md
> Add Go documentation

- README.md
Addressing your comment, @honzajavorek.
> Link to add new langauge

- docs/hooks-new-language.md
To address @XVincentX's comment here: https://github.com/apiaryio/dredd-hooks-template/issues/5
> Updated doc on new look language

- .travis.yml
> Remove hipchat notifications from Travis CI

- docs/hooks-ruby.md
> Fix syntax typo in docs example

- docs/hooks-perl.md
Added perl userguide as requested in #364
> Added Perl Dredd Hooks userguide

- README.md
- docs/hooks-new-language.md
- docs/hooks-perl.md
- docs/hooks-php.md
- docs/hooks.md
- docs/index.md
- mkdocs.yml
- scripts/test-hook-handlers.coffee
- src/dredd-command.coffee
- src/hooks-worker-client.coffee
> Adding Perl

- ApiaryReportingApi.md
- package.json
- scripts/cov
- scripts/stress-build
- src/add-hooks.coffee
- src/dredd-command.coffee
- src/dredd.coffee
- src/hooks-worker-client.coffee
- src/hooks.coffee
- src/reporters/apiary-reporter.coffee
- src/transaction-runner.coffee
- test/fixtures/scripts/endless-nosigterm.sh
- test/fixtures/scripts/endless-sigterm.sh
- test/fixtures/scripts/exit_1.sh
- test/fixtures/scripts/exit_2.sh
- test/fixtures/scripts/kill-self.sh
- test/fixtures/scripts/stderr.sh
- test/integration/cli-test.coffee
- test/integration/dredd-command-test.coffee
- test/integration/dredd-test.coffee
- test/unit/add-hooks-test.coffee
- test/unit/dredd-command-test.coffee
- test/unit/hooks-worker-client-test.coffee
- test/unit/reporters/apiary-reporter-test.coffee
- test/unit/transaction-runner-test.coffee
before:
```
734 passing (4m)
real    4m20.975s
user    2m24.796s
sys     0m5.835s
```
after:
```
820 passing (2m)
real	2m15.007s
user	0m43.701s
sys     0m5.653s
```
> Big refactoring and optimisation of hook handler spawner and client

- src/dredd.coffee
- test/integration/cli/api-description-cli-test.coffee
- test/unit/dredd-test.coffee
> Wrong callback variable name

- mkdocs.yml
This adds permalinks to the rendered Dredd documentation.
> Add permalinks to headings

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- VirtualDevelopmentEnvironment.md
- package.json
:memo: :notebook: :notebook_with_decorative_cover: :memo: :green_book: :blue_book: :book: :books: :memo:
- Updated Changelog.
- Updated `package.json` so it reflects reality.
- Added `CONTRIBUTING.md` with Quick Start for contributors and more elaborate section called Handbook, which explain certain infrastructure around Dredd's codebase.
- Facelift of README.
> Updated Docs & Changelog

- package.json
> Pinned Protagonist to 1.2.6.

- CONTRIBUTING.md
- package.json
- scripts/cov
- scripts/test
- scripts/test-stress
- test/mocha.opts
Leveraging mocha.opts to DRY out Mocha configuration.
> mocha.opts

- docs/hooks-new-language.md
- docs/usage.md
- src/apply-configuration.coffee
- src/hooks-worker-client.coffee
- src/options.coffee
- test/unit/hooks-worker-client-test.coffee
This takes @xvalentino's amazing work from https://github.com/apiaryio/dredd/pull/382 and addresses @netmilk's comments.
Closes #328 :tada:
Closes #272 :tada:
Closes #382 :tada:
> Pass in options to hook worker (continued)

- docs/hooks-new-language.md
- package.json
- scripts/cov
- src/options.coffee
- test/unit/add-hooks-test.coffee
- test/unit/hooks-test.coffee
- test/unit/transaction-runner-test.coffee
> Little Polishing

- src/reporters/apiary-reporter.coffee
> Add `BUILD_ID` to apiary reporter CI var check

- CHANGELOG.md
- package.json
- test/fixtures/regression-319-354.apib
- test/regressions/regression-319-354-test.coffee
Upgrading to newest Protagonist.
- Closes https://github.com/apiaryio/dredd/pull/380.
- Fixes #354.
- Fixes #381.
- Fixes #291.
> Protagonist 1.3.0

- CHANGELOG.md
- package.json
> v1.1.0 pre.0

- docs/overview.md
Updates doc with suggested method for replacing url params described in #186 .
> Docs update of hook example code for replacing URL params

- CHANGELOG.md
- docs/usage-cli.md
- package.json
- scripts/generate-cli-docs.coffee
- src/reporters/apiary-reporter.coffee
Closes https://github.com/apiaryio/dredd/issues/471.
> v1.1.0 pre.1

- docs/usage/index.html
- mkdocs.yml
Fixes #467. Follow-up to https://github.com/apiaryio/dredd/pull/489.
> Redirect /usage to /usage-cli

- CHANGELOG.md
- package.json
- test/fixtures/error-blueprint.apib
- test/unit/handle-runtime-problems-test.coffee
Using Dredd Transactions which are built on top of Fury.js.
> v1.1.0-pre.3

- CHANGELOG.md
- CONTRIBUTING.md
- package.json
> v1.1.0 pre.4

- CHANGELOG.md
- package.json
- src/hooks-worker-client.coffee
Depends on https://github.com/apiaryio/dredd-transactions/pull/38.
> v1.1.0 pre.5

- CONTRIBUTING.md
- docs/overview.md
- package.json
- scripts/print-installation-guidelines.coffee
- src/transaction-runner.coffee
Addressing most of the https://github.com/apiaryio/dredd/issues/497.
Note that until next major release, regardless what docs say, we'll keep the original behavior and we'll have `stable` tag at the same time: https://github.com/apiaryio/dredd/issues/497#issuecomment-222971514
> Introducing the stable tag

- CHANGELOG.md
- package.json
Finalizing experimental support for Swagger.
> v1.1.0 pre.6

- .npmignore
- CHANGELOG.md
- package.json
Hotfix of broken Dredd installation.
> v1.1.0 pre.7

- scripts/test-hooks-handlers.coffee
Let's see whether everything works together!
> Added Go to hook handlers integration tests

- package.json
I believe people from https://github.com/apiaryio/dredd/issues/438 will cheer about this :wink:
> Make repo commitizen-friendly

- CHANGELOG.md
- docs/how-it-works.md
- package.json
> Use default value even though the parameter is required

- .travis.yml
- CHANGELOG.md
- package.json
- scripts/cov
- test/unit/blueprint-utils-test.coffee
- Dredd is now installable also without C++ compiler
- Contains also bug fix for https://github.com/apiaryio/dredd/pull/570
> Dredd is now installable also without C++ compiler

- README.md
- docs/index.md
> Swagger support is not considered experimental anymore

- package.json
**Please do not merge this before https://github.com/apiaryio/dredd/pull/595 gets merged.**
------
See https://github.com/apiaryio/dredd/issues/578#issuecomment-238690521 for details (cc @abtris @netmilk )
> Putting back upstream html package

- LICENSE
**Please do not merge this before https://github.com/apiaryio/dredd/pull/595 gets merged.**
Also, ignore failing Snyk check, it's already resolved in both `master` and https://github.com/apiaryio/dredd/pull/592.
> Update LICENSE file so it's aligned with package.json

- src/transaction-runner.coffee
- test/integration/cli/server-process-cli-test.coffee
- test/unit/transaction-runner-test.coffee
Adressing https://github.com/apiaryio/dredd/issues/260.
**Code review hint:** Go commit by commit
> More benevolent server address

- scripts/test-hooks-handlers.coffee
Fixes #601 (https://github.com/semantic-release/semantic-release/issues/273)
Hint for code review: **Go commit by commit**
> Fix dependent builds

- src/dredd.coffee
- src/reporters/dot-reporter.coffee
- test/unit/reporters/dot-reporter-test.coffee
Closes https://github.com/apiaryio/dredd/issues/594.
There was a missing callback in the `start` event.
> Fixed dot reporter

- src/dredd-command.coffee
- src/parse-package-json.coffee
- src/reporters/apiary-reporter.coffee
- src/transaction-runner.coffee
- test/integration/dredd-command-test.coffee
- test/integration/dredd-test.coffee
- test/unit/dredd-command-test.coffee
> Unified and simplified package.json and version handling

- src/dredd-command.coffee
Addressing the simplest item from https://github.com/apiaryio/dredd/issues/625.
> Report OS type and version in dredd --version

- package.json
There were couple of fixes in how Fury Swagger adapter processes Swagger.
- https://github.com/apiaryio/dredd-transactions/pull/67
- https://github.com/apiaryio/fury-adapter-swagger/pull/79
- https://github.com/apiaryio/fury-adapter-swagger/pull/81
- https://github.com/apiaryio/fury-adapter-swagger/pull/84
- https://github.com/apiaryio/fury-adapter-swagger/pull/86
- https://github.com/apiaryio/fury-adapter-swagger/pull/87
- https://github.com/apiaryio/fury-adapter-swagger/pull/89
> Get Swagger fixes from the latest Dredd Transactions

- .github/PULL_REQUEST_TEMPLATE.md
Because docs are important and almost always needed 📚 
- https://github.com/apiaryio/dredd/pull/640
> Add docs to PR template

- src/transaction-runner.coffee
It better reflects what the code does.
- #648
> Use better variable name

- src/transaction-runner.coffee
- test/unit/transaction-runner-test.coffee
I've got this issue as well and found an un-mergeable pull request open. This is my attempt at rebasing it.
Bare with me, it's my first PR in coffee script!
Not sure if this requires writing some doc, let me know if so.
Fixes #93
Replaces #258
> Keep forward slashes in URL if they're present

- .travis.yml
Reason: https://github.com/apiaryio/dredd/issues/672
> Temporarily disable hook handlers intergration tests

- docs/how-it-works.md
> docs: Fix link to Apiary Privacy Policy

- docs/hooks-python.md
There is incorrect logic in the documentation
Issue #719 
- [:white_check_mark:] To write docs
- [N/A] To write tests
- [:white_check_mark:] To put [Conventional Changelog](https://dredd.readthedocs.io/en/latest/contributing/#sem-rel) prefixes in front of all my commits and run `npm run lint`
> docs: Fix error in hooks-python.md

- .github/CONTRIBUTING.md
Codifying recent changes.
Follow-up to #732 and #738.
> Add recent changes to misc tips in contributing docs

- docs/installation.md
> Missing colon

- package.json
The new version of Dredd Transactions contains various fixes and new interfaces in the parsing toolchain. This will enable us to fully use the power of the newest version of [API Elements](https://api-elements.readthedocs.io/en/latest/overview/).
> Update Dredd Transactions

- package.json
Fixes https://snyk.io/vuln/npm:pidusage:20170605
- #805
> Update Pitboss to fix a vulnerability CWE-77

- docs/hooks-go.md
- docs/hooks-perl.md
- docs/hooks-php.md
- docs/hooks-python.md
- docs/hooks-ruby.md
Bad formatting hinders readability.
None
> Fix the numbered list in hook files

- docs/hooks-go.md
Examples fail to compile.
This change was previously contributed by @m00sey in https://github.com/apiaryio/dredd/pull/809/ 👏 However, the commits were missing the Conventional Changelog prefixes. When we've got that fixed, the demon of git complexity fought back and we've got two commits without prefixes, two commits with prefixes, and one suspicious merging commit. That delayed accepting the PR for rather longer time. In this PR, I'd like to fix the situation and to finally get @m00sey's wonderful changes merged!
Closes https://github.com/apiaryio/dredd/pull/809/
> Update Go hooks docs

- .travis.yml
- package.json
See https://github.com/apiaryio/dredd/issues/828 for explanation.
- https://github.com/apiaryio/dredd/pull/775
- https://github.com/apiaryio/dredd/issues/828
> Hotfix: Do not use trusty Travis CI infrastructure

- package.json
The latest version of Dredd Transaction fixes recent regression bugs.
Closes https://github.com/apiaryio/dredd/issues/872
Closes https://github.com/apiaryio/dredd/issues/870
> Fix enum URI parameters, fix Swagger with auth & multi responses

- package.json
This PR updates `dredd-transactions` package to version `4.3.4` (explicitly) to introduce remaining parts of rewrite to `minim`).
> Upgrade dredd-transactions

- package.json
- src/dredd.coffee
- src/flatten-headers.coffee
- src/handle-runtime-problems.coffee
- src/transaction-runner.coffee
- test/unit/handle-runtime-problems-test.coffee
Propagating https://github.com/apiaryio/dredd-transactions/issues/9 and https://github.com/apiaryio/dredd-transactions/issues/19 to Dredd.
- Enables https://github.com/apiaryio/dredd/issues/356
> Upgrade to simpler Dredd Transactions interface

- package.json
There has been some fixes and changes in the Fury toolchain. This introduces them to Dredd.
- https://github.com/apiaryio/dredd-transactions/pull/135
- https://github.com/apiaryio/dredd-transactions/pull/139
- https://github.com/apiaryio/dredd-transactions/pull/140
> Update Fury toolchain (parsing)

- README.md
More resources on Dredd from around the internet for new-commers. Saves googling and global warming.
> docs: Adding list of 3rd party articles on Dredd to the Readme

- README.md
> chore: Fixed formatting

- package.json
Propagation of `dredd-transactions` version bump.
> Upgrade dredd-transactions to 6.0.1

- package.json
Note: Already pre-approved in TPLTA.
> Upgrade request to 2.83.0

- package.json
> fix(package): Update dredd-transactions to 6.0.2

- package.json
> fix(package): Update dredd-transactions to 6.1.0

- README.md
> Add Phil's article mentioning Dredd

- package.json
Looks like the licensing conflicts are solved according to #1059.
Closes #1059
> Update request to 2.87

- package-lock.json
- package.json
- test/unit/add-hooks-test.js
- test/unit/configure-reporters-test.js
- test/unit/dredd-test.js
- test/unit/hooks-log-sandboxed-test.js
- test/unit/hooks-log-test.js
- test/unit/init/applyAnswers-test.js
- test/unit/performRequest/normalizeContentLengthHeader-test.js
- test/unit/performRequest/performRequest-test.js
- test/unit/transaction-runner-test.js
- After merging https://github.com/apiaryio/dredd/pull/1085 the lock file is out of sync
- Upgrade sinon
- https://github.com/apiaryio/dredd/pull/1085
- #1052
> Update sinon to 6.1.5

- docs/conf.py
- docs/installation.rst
- docs/internals.rst
- docs/quickstart.rst
- docs/requirements.txt
The guide is incomplete and doesn't capture many pitfalls users can meet. We're now also adding an official Docker support. This PR also adds a support for tabbed content to the docs as a side-effect.
- Resolve the core of https://github.com/apiaryio/dredd/issues/904
- Close https://github.com/apiaryio/dredd/issues/999
- Close https://github.com/apiaryio/docker-base-images/issues/130
- Mitigate https://github.com/apiaryio/dredd/issues/659
- Write a dedicated page about Continuous Integration and tackle https://github.com/apiaryio/dredd/issues/353
- Revamp quickstart as it is tightly connected to the first time user experience - https://github.com/apiaryio/dredd/issues/904 (this resolves the rest of https://github.com/apiaryio/dredd/issues/904)
- Document using Docker with the server …
> New installation guide

- .eslintrc.js
I changed my mind. When I look at https://github.com/apiaryio/dredd/pull/1173, it only adds complexity for no reason.
Close https://github.com/apiaryio/dredd/pull/1173
> Allow console

- package.json
To stay up to date and to minimize vulnerability risks.
Close #1201, close #1199, close #1198
> Update @commitlint libs to version 7.3.1

- package.json
Not sure why these weren't picked up by greenkeeper but they all seem save as their dependency ranges didn't change much if at all.
> Update some dependencies

- package.json
I suspect this one is more of a licensing hassle but it will bring almost all (non-dev) dependencies to their most current version. 🎉
> fix(package): update request to version 2.88.0

- README.md
> Add an article to the README

- package.json
- test/integration/regressions/regression-319-354-test.js
See [Drafter Changelog](https://github.com/apiaryio/drafter/releases).
> Use Drafter v4 for parsing API Blueprint

- package.json
> Avoid vulnerabilities

- package.json
> Upgrade CoffeeScript

- docs/hooks/php.rst
> docs: add missing parenthesis in example

- docs/hooks/index.rst
Fix https://github.com/apiaryio/dredd/issues/1271
> Fix link for transactions on hooks page

- README.md
> Add interview with SurviveJS

- lib/Dredd.js
- lib/resolveModule.js
- test/fixtures/requiredModule.js
- test/integration/require-test.js
- test/unit/resolveModule-test.js
Factored out from https://github.com/apiaryio/dredd/pull/1289/
> Refactor and test requiring user-provided module

- docs/requirements.txt
Mitigating https://snyk.io/vuln/SNYK-PYTHON-JINJA2-174126
> Upgrade jinja2

- README.md
https://twitter.com/ITNetworkfr/status/1126486367767277568
Be careful, this blogpost is in french :sweat_smile:
> Add a blogpost to the readme

- package.json
Updating the validation engine.
Closes #1383
> fix(package): update gavel to version 4.0.1

- package.json
Close https://github.com/apiaryio/dredd/pull/1389
> Upgrade commitlint

- package.json
https://github.com/apiaryio/dredd-transactions/pull/313
> Introduce several fixes for OAS

- lib/TransactionRunner.js
- package.json
- test/fixtures/sanitation/plain-text-response-body.js
- test/fixtures/sanitation/response-body-attribute.js
- test/fixtures/sanitation/response-headers.js
- test/integration/apiary-reporter-test.js
- test/integration/cli/reporters-cli-test.js
- test/integration/response-test.js
- test/integration/sanitation-test.js
- Installs and updates Dredd to use Gavel version 7
- Provides small utilities for sanitation hooks in integration tests to prevent repetition
> Updates Gavel to version 7

- .travis.yml
- test/integration/require-test.js
- See #1396 for motivation
- Closes #1396
> chore: adds "node12" job to travis ci

- README.md
- docs/index.rst
- docs/quickstart.rst
https://commandz.io/snippets/laravel/laravel-dredd-openapi-v3/
> Add laravel blogpost and example app by @AndyWendt

- package.json
For https://github.com/apiaryio/dredd/pull/1526
> Add the prettier dependency

- packages/dredd-transactions/package.json
- yarn.lock
Upgrades the parser toolchain to the latest version.
> Upgrade fury to 3.0.0-beta.13

- packages/dredd-transactions/package.json
- packages/dredd/package.json
- packages/dredd/scripts/smoke.sh
- Updated fury toolchain (https://github.com/apiaryio/dredd/pull/1623)
- Added support for JSON Schema Draft 6 and 7 (https://github.com/apiaryio/dredd/pull/1622)
> Release dredd 12.2.0

- packages/dredd-transactions/package.json
- packages/dredd/package.json
- To release a next version of `dredd` and `dredd-transactions` that contain updated Fury adapters
> Release dredd to 12.2.1, dredd-transactions to 9.1.1

- packages/dredd/package.json
- Drops support for JSON Schema Draft V3
- No related issues, governance task
> chore: releases dredd@13.0.0

- packages/dredd-transactions/package.json
- packages/dredd/package.json
- dredd@13.0.1
- dredd-transactions@9.1.2
- Contains the latest `fury-adapter-swagger` (https://github.com/apiaryio/dredd/pull/1668)
- No related issues, governance
> Releases "dredd-transactions@9.1.2"

- packages/dredd-transactions/package.json
- packages/dredd-transactions/parse/index.js
- packages/dredd-transactions/scripts/pretest.js
- packages/dredd-transactions/test/fixtures/index.js
- packages/dredd-transactions/test/unit/compileAnnotation-test.js
- packages/dredd-transactions/test/unit/compileURI/compileParams-test.js
- packages/dredd-transactions/test/unit/parse-test.js
- yarn.lock
fury has been renamed to @apielements/core
> Upgrade fury to @apielements/core

- .github/workflows/run-docs-test.yml
- .github/workflows/run-e2e-tests.yml
- .github/workflows/run-test.yml
- scripts/commitlint.sh
lint and run test on push to repository
testing general tests, e2e tests and docs tests.
Moving to GitHub actions from Circle-CI
> chore(gh-actions): add general test run

- RELEASE.md
Adds the release process documentation.
- Documents #1621
> chore: add release docs

- docs/data-structures.rst
```
Warning, treated as error:
/home/circleci/project/docs/data-structures.rst.rst:7:broken link: mson ()
error Command failed with exit code 2.
```
> doc: fix MSON link

- packages/dredd-transactions/package.json
- packages/dredd/package.json
Releases the next versions of Dredd and dredd-transactions.
> chore: release dredd 14.1.0
